/* かんじすたんしょん - キャラクターの個性
 *
 * いまは小学1年の40字ぶん。ほかの学年の漢字は共通デザインのまま。
 * 学年を増やすときは、ここにエントリを足すだけでよい（app.js の変更は不要）。
 *
 *   name  … キャラの なまえ
 *   voice … 問題に出てきたときの ひとこと
 *   win   … 正解したときの ひとこと
 *   lose  … まちがえたときの ひとこと
 *   zukan … ずかんの じこしょうかい
 *   sc    … はいけいの え（app.js の SCENES のキー）
 *   ov    … かおに かさねる もの（app.js の OVERLAYS のキー。あたまに のる curl/ribbon/cap は
 *           ★4以上で ぼうし・おうかんに ばしょを ゆずる）
 *   eyes  … round / dot / wink / sparkle / sleepy / closed
 *   mouth … smile / open / small / tooth / wave
 */

const CHARA = {
  '町': { name:'まちお', sc:'town', eyes:'round', mouth:'smile',
    voice:'ぼくの まわりは おみせだらけ！',
    win:'まちの みんなも よろこんでるよ！',
    lose:'まちで まいご に なっちゃった…',
    zukan:'いえや おみせが あつまった ところ。「〇〇町」という えきは とても おおいよ。' },
  '田': { name:'たんた', sc:'rice', eyes:'sleepy', mouth:'small',
    voice:'たんぼで おこめを そだてて いるよ',
    win:'ことしも ほうさく だあ！',
    lose:'すずめに たべられちゃった…',
    zukan:'おこめを つくる ばしょ。「田んぼ」の ほかに「田舎（いなか）」の ような よみも あるよ。' },
  '川': { name:'かわたろう', sc:'water', eyes:'round', mouth:'wave',
    voice:'ぼく、ずーっと ながれて いるよ',
    win:'ざぶーん！ ながれに のったね',
    lose:'ながされちゃった〜！',
    zukan:'みずが ながれる みち。ちいさいと「小川（おがわ）」、おおきいと「河川（かせん）」。' },
  '大': { name:'だいちゃん', sc:'big', eyes:'round', mouth:'open',
    voice:'おいら なんでも でっかいぞ！',
    win:'でっかい せいかい！ あっぱれ！',
    lose:'うーん、おおきく はずれた…',
    zukan:'おおきい こと。「大きい」「大学」「大人（おとな）」…よみかたが とても おおい かんじ。' },
  '五': { name:'ごーくん', sc:'five', eyes:'wink', mouth:'smile',
    voice:'ゆびは ぜんぶで 五ほん だよ',
    win:'五つぼしの せいかい！',
    lose:'ゆびおり かぞえて みよう',
    zukan:'かずの 5。「五日（いつか）」「五月雨（さみだれ）」のように よみが かわるよ。' },
  '目': { name:'めめ', sc:'shine', ov:'glasses', eyes:'sparkle', mouth:'small',
    voice:'なんでも よーく みえるんだ',
    win:'ぱっちり！ よく みえたね',
    lose:'めがねが くもって しまった…',
    zukan:'ものを みる ところ。「目次（もくじ）」「面目（めんぼく）」のように「もく」「ぼく」とも よむ。' },
  '木': { name:'きのすけ', sc:'tree', eyes:'round', mouth:'smile',
    voice:'はっぱが そよそよ するよ',
    win:'えだが ぐんと のびた きぶん！',
    lose:'はっぱが いちまい おちた…',
    zukan:'き の こと。「木（き）」「木曜日（もく）」「大木（たいぼく）」。' },
  '白': { name:'しろまる', sc:'cloud', eyes:'closed', mouth:'small',
    voice:'まっしろ。よごれて ないでしょ？',
    win:'しろぼしを ひとつ ゲット！',
    lose:'くろぼしに なっちゃった…',
    zukan:'しろい いろ。「白紙（はくし）」「白髪（しらが）」など よみが かわる。' },
  '日': { name:'ひーちゃん', sc:'sun', eyes:'sparkle', mouth:'open',
    voice:'あさだよ！ おはよう！',
    win:'きょうは いい ひ に なったね',
    lose:'くもって きちゃった…',
    zukan:'たいようと ひにち。「日曜日」「今日（きょう）」「一日（ついたち）」…よみが にほんいち おおい かんじ。' },
  '上': { name:'うえぞう', sc:'up', eyes:'round', mouth:'smile',
    voice:'うえだよ うえ！ のぼろう！',
    win:'ひとつ うえに いったね！',
    lose:'あしを すべらせた…',
    zukan:'うえの ほう。「上（うえ）」「上る（のぼる）」「上手（じょうず）」。' },
  '水': { name:'みずき', sc:'water', eyes:'round', mouth:'wave',
    voice:'ぴちゃん。つめたいよ',
    win:'すいすい せいかい！',
    lose:'ぽちゃん。しずんじゃった',
    zukan:'みず。「水（みず）」「水泳（すいえい）」「清水（しみず）」。' },
  '四': { name:'よんちゃん', sc:'four', eyes:'dot', mouth:'small',
    voice:'しかくが だいすき なの',
    win:'よっつ そろって だいせいかい！',
    lose:'ひとつ たりなかった…',
    zukan:'かずの 4。「四つ（よっつ）」「四日（よっか）」「四季（しき）」。' },
  '中': { name:'なかお', sc:'target', eyes:'round', mouth:'smile',
    voice:'まんなかが ぼくの ばしょ',
    win:'ど まんなか！ めいちゅう！',
    lose:'ちょっと はずれた…',
    zukan:'まんなか。「中（なか）」「中学（ちゅう）」「一日中（じゅう）」。' },
  '円': { name:'えんまる', sc:'coin', eyes:'wink', mouth:'smile',
    voice:'まるいよ。おかねの たんい だよ',
    win:'まるく おさまった！',
    lose:'ころころ ころがって いった…',
    zukan:'まる と おかね。「百円（えん）」「円い（まるい）」「円周（えんしゅう）」。' },
  '三': { name:'さんた', sc:'three', eyes:'round', mouth:'tooth',
    voice:'いち、に、さん！ さんばん だよ',
    win:'さんかい まわって せいかい！',
    lose:'さんねん…もとい、ざんねん…',
    zukan:'かずの 3。「三日（みっか）」「三味線（しゃみせん）」なんて よみも あるよ。' },
  '小': { name:'こつぶ', sc:'small', eyes:'dot', mouth:'small',
    voice:'ちいさいけど すばやいよ',
    win:'ちいさな からだで おおきな せいかい！',
    lose:'ちいさく なって かくれちゃう…',
    zukan:'ちいさい こと。「小さい」「小学校（しょう）」「小川（おがわ）」「小豆（あずき）」。' },
  '金': { name:'きんじ', sc:'shine', eyes:'sparkle', mouth:'smile',
    voice:'ぴかー！ ひかってる？',
    win:'きんメダル あげちゃう！',
    lose:'ぴかぴかが きえちゃった…',
    zukan:'きんいろ と おかね。「お金（かね）」「金曜日（きん）」「黄金（おうごん）」。' },
  '立': { name:'たっち', sc:'stand', eyes:'round', mouth:'open',
    voice:'しゃきーん！ たったよ',
    win:'かっこよく たてたね！',
    lose:'ぐらぐら…ころんじゃった',
    zukan:'たつ こと。「立つ」「国立（りつ）」「夕立（ゆうだち）」。' },
  '八': { name:'はっちゃん', sc:'eight', eyes:'wink', mouth:'smile',
    voice:'すえひろがりで えんぎが いいんだ',
    win:'はちまき しめて せいかい！',
    lose:'ちょっと まがっちゃった…',
    zukan:'かずの 8。「八日（ようか）」「八百屋（やおや）」は とくべつな よみ。' },
  '王': { name:'おうさま', sc:'crownbg', eyes:'round', mouth:'tooth',
    voice:'われこそ おうで ある！',
    win:'みごと！ ほうびを とらせよう',
    lose:'むむ…おうも まちがえる ことが ある',
    zukan:'くにで いちばん えらい ひと。「王さま（おう）」「王子（おうじ）」「女王（じょおう）」。' },
  '子': { name:'こっこ', sc:'star', ov:'curl', eyes:'round', mouth:'open',
    voice:'ぼく まだ ちっちゃいんだ',
    win:'すごーい！ おにいさん みたい！',
    lose:'えーん、むずかしいよう',
    zukan:'こども。「子ども（こ）」「様子（す）」「弟子（でし）」「椅子（いす）」。' },
  '草': { name:'くさすけ', sc:'grass', eyes:'sleepy', mouth:'smile',
    voice:'はらっぱで ごろごろ してる',
    win:'くさむらから ひょっこり！',
    lose:'くさに かくれちゃった…',
    zukan:'くさ。「草（くさ）」「草原（そうげん）」「雑草（ざっそう）」。' },
  '糸': { name:'いとまき', sc:'thread', eyes:'round', mouth:'small',
    voice:'くるくる まかれて いるよ',
    win:'うまく ときほぐせたね！',
    lose:'こんがらがって しまった…',
    zukan:'いと。「糸（いと）」「毛糸（けいと）」「製糸（せいし）」。' },
  '本': { name:'ほんちゃん', sc:'book', eyes:'sparkle', mouth:'smile',
    voice:'よむのが だいすき！',
    win:'1ページ すすんだ かんじ！',
    lose:'ページを めくり まちがえた…',
    zukan:'ほん と もと。「本（ほん）」「日本（にほん）」「本音（ほんね）」。' },
  '下': { name:'したろう', sc:'down', eyes:'round', mouth:'small',
    voice:'したへ どうぞ〜',
    win:'したから ささえて あげたよ',
    lose:'おっこちて しまった…',
    zukan:'したの ほう。「下（した）」「地下（ちか）」「下山（げざん）」「下手（へた）」。' },
  '山': { name:'やまじい', sc:'mountain', eyes:'closed', mouth:'smile',
    voice:'どっしり かまえて おるぞ',
    win:'いただきまで のぼったのう！',
    lose:'まだ ごうめ あたりじゃ…',
    zukan:'やま。「山（やま）」「火山（かざん）」「山車（だし）」。' },
  '見': { name:'みっけ', sc:'shine', eyes:'sparkle', mouth:'open',
    voice:'あっ！ なにか みつけた！',
    win:'よく みつけたね！',
    lose:'みのがして しまった…',
    zukan:'みる こと。「見る」「見学（けん）」「発見（はっけん）」。' },
  '千': { name:'せんちゃん', sc:'many', eyes:'round', mouth:'smile',
    voice:'1000 だよ。いっぱい あるよ',
    win:'せんにんりき だね！',
    lose:'かぞえきれなかった…',
    zukan:'かずの 1000。「千円（せん）」「千代紙（ちよがみ）」。' },
  '口': { name:'くちお', sc:'speech', eyes:'round', mouth:'open',
    voice:'ぱくぱく。おしゃべり だいすき',
    win:'よく こえに だせたね！',
    lose:'あわわ…かんじゃった',
    zukan:'くち。「口（くち）」「人口（じんこう）」「早口（はやくち）」。' },
  '赤': { name:'あかね', sc:'red', ov:'ribbon', eyes:'wink', mouth:'smile',
    voice:'まっかっか。もえて いるよ',
    win:'あかい リボン あげる！',
    lose:'かおが まっかに なっちゃう…',
    zukan:'あかい いろ。「赤い（あか）」「赤ちゃん」「赤道（せきどう）」。' },
  '十': { name:'じゅうた', sc:'cross', eyes:'round', mouth:'tooth',
    voice:'じゅっこ そろって いるよ',
    win:'まんてん！ じゅうぶん だね',
    lose:'ひとつ たりない かな…',
    zukan:'かずの 10。「十日（とおか）」「十字路（じゅう）」。' },
  '天': { name:'てんちゃん', sc:'sky', eyes:'sparkle', mouth:'small',
    voice:'そらの うえに いるんだ',
    win:'てんきに なったよ！',
    lose:'あめが ふって きた…',
    zukan:'そら。「天気（てん）」「天の川（あま）」「天女（てんにょ）」。' },
  '学': { name:'がっくん', sc:'book', ov:'cap', eyes:'round', mouth:'smile',
    voice:'べんきょう しよう！ たのしいよ',
    win:'かしこく なったね！',
    lose:'もういちど ふくしゅう しよう',
    zukan:'まなぶ こと。「学校（がく・がっ）」「大学（だい）」「学ぶ（まなぶ）」。' },
  '名': { name:'なーちゃん', sc:'nametag', eyes:'round', mouth:'smile',
    voice:'きみの なまえ、なんて いうの？',
    win:'なまえを おぼえたよ！',
    lose:'なまえを わすれちゃった…',
    zukan:'なまえ。「名前（な）」「名人（めい）」「名字（みょうじ）」。' },
  '生': { name:'いくる', sc:'sprout', eyes:'sparkle', mouth:'open',
    voice:'ぐんぐん そだつよ！',
    win:'いきいき して きたね！',
    lose:'みずが たりなかった…',
    zukan:'いきる・うまれる。「生きる」「先生（せい）」「一生（しょう）」「芝生（しばふ）」。' },
  '百': { name:'ひゃっくん', sc:'hundred', eyes:'sparkle', mouth:'tooth',
    voice:'100てん とりたいな！',
    win:'はなまる 100てん！',
    lose:'99てん…おしい！',
    zukan:'かずの 100。「百円（ひゃく）」「三百（びゃく）」「八百屋（やおや）」。' },
  '玉': { name:'たまちゃん', sc:'ball', eyes:'round', mouth:'smile',
    voice:'ころころ ころがるよ',
    win:'ナイス キャッチ！',
    lose:'ころころ にげちゃった…',
    zukan:'たま。「玉（たま）」「水玉（みずたま）」「埼玉（たま）」「玉石（ぎょく）」。' },
  '花': { name:'はなこ', sc:'flower', ov:'ribbon', eyes:'wink', mouth:'small',
    voice:'いい におい するでしょ？',
    win:'ぱっと はなが さいたよ！',
    lose:'しおれちゃった…みずを ちょうだい',
    zukan:'はな。「花（はな）」「花火（はなび）」「花だん（か）」。' },
  '村': { name:'むらた', sc:'house', eyes:'round', mouth:'smile',
    voice:'みんなで なかよく くらしてる',
    win:'むらじゅうで おいわいだ！',
    lose:'むらの みんなも しょんぼり…',
    zukan:'むら。「村（むら）」「村人（むらびと）」「農村（のうそん）」。' },
  '石': { name:'いしまる', sc:'stone', eyes:'dot', mouth:'tooth',
    voice:'かたいぞ！ わられないぞ',
    win:'いしのように かたい せいかい！',
    lose:'ごろん。ころがって しまった',
    zukan:'いし。「石（いし）」「石油（せき）」「磁石（じしゃく）」「石高（こくだか）」。' }
};
