// でんしゃで おふろやさん — データ
// {漢字|よみ} は ふりがな つきで ひょうじ される。
// at   : { えきめい: 'えきからの いきかた' } … おなじ おふろを いくつかの えきに だせる
// open : [あく ふん, しまる ふん]（24じ いこうは 1440 より おおきい かず）
// openDow : ようびごとの じかん { 0:にちようび … 6:どようび }
// rest : dow=ようび / date=ひにち / nth=[{dow,n,months}] だい n ○ようび / until=この ひまで おやすみ

const SEN = {
  tokyo:    'こども 200えん（6〜11さい）／ ちいさい こ 100えん',
  saitama:  'こども 200えん（6〜11さい）／ ちいさい こ 100えん',
  kanagawa: 'こども 250えん（6〜11さい）／ ちいさい こ 130えん'
};

const LINES = [
  {
    id: 'blue', name: 'ブルーライン', sub: 'よこはま しえい ちかてつ', color: '#0b78be',
    stations: [
      '{湘南台|しょうなんだい}', '{下飯田|しもいいだ}', '{立場|たてば}', '{中田|なかだ}', '{踊場|おどりば}',
      '{戸塚|とつか}', '{舞岡|まいおか}', '{下永谷|しもながや}', '{上永谷|かみながや}', '{港南中央|こうなんちゅうおう}',
      '{上大岡|かみおおおか}', '{弘明寺|ぐみょうじ}', '{蒔田|まいた}', '{吉野町|よしのちょう}', '{阪東橋|ばんどうばし}',
      '{伊勢佐木長者町|いせざきちょうじゃまち}', '{関内|かんない}', '{桜木町|さくらぎちょう}', '{高島町|たかしまちょう}', '{横浜|よこはま}',
      '{三ツ沢下町|みつざわしもちょう}', '{三ツ沢上町|みつざわかみちょう}', '{片倉町|かたくらちょう}', '{岸根公園|きしねこうえん}', '{新横浜|しんよこはま}',
      '{北新横浜|きたしんよこはま}', '{新羽|にっぱ}', '{仲町台|なかまちだい}', 'センター{南|みなみ}', 'センター{北|きた}',
      '{中川|なかがわ}', 'あざみ{野|の}'
    ]
  },
  {
    id: 'keihin', name: 'けいひんとうほく・ねぎしせん', sub: 'JR', color: '#00a7db',
    stations: [
      { sep: 'さいたまけん' },
      '{大宮|おおみや}', 'さいたま{新都心|しんとしん}', '{与野|よの}', '{北浦和|きたうらわ}', '{浦和|うらわ}',
      '{南浦和|みなみうらわ}', '{蕨|わらび}', '{西川口|にしかわぐち}', '{川口|かわぐち}',
      { sep: 'とうきょうと' },
      '{赤羽|あかばね}', '{東十条|ひがしじゅうじょう}', '{王子|おうじ}', '{上中里|かみなかざと}', '{田端|たばた}',
      '{西日暮里|にしにっぽり}', '{日暮里|にっぽり}', '{鶯谷|うぐいすだに}', '{上野|うえの}', '{御徒町|おかちまち}',
      '{秋葉原|あきはばら}', '{神田|かんだ}', '{東京|とうきょう}', '{有楽町|ゆうらくちょう}', '{新橋|しんばし}',
      '{浜松町|はままつちょう}', '{田町|たまち}', '{高輪|たかなわ}ゲートウェイ', '{品川|しながわ}', '{大井町|おおいまち}',
      '{大森|おおもり}', '{蒲田|かまた}',
      { sep: 'かながわけん' },
      '{川崎|かわさき}', '{鶴見|つるみ}', '{新子安|しんこやす}', '{東神奈川|ひがしかながわ}', '{横浜|よこはま}',
      '{桜木町|さくらぎちょう}', '{関内|かんない}', '{石川町|いしかわちょう}', '{山手|やまて}', '{根岸|ねぎし}',
      '{磯子|いそご}', '{新杉田|しんすぎた}', '{洋光台|ようこうだい}', '{港南台|こうなんだい}', '{本郷台|ほんごうだい}',
      '{大船|おおふな}'
    ]
  }
];

const H = (h, m = 0) => h * 60 + m;

const BATHS = [
  /* ───────── ブルーライン ───────── */
  { id:'kuzunoyu', at:{'踊場':'🚶 あるいて 10ぷん'}, icon:'🌳', name:'{葛|くず}の{湯|ゆ}', kind:'せんとう',
    open:[H(10), H(24)], rest:{dow:[4]}, restText:'もくようび',
    feat:['onsen','roten','utase','sauna','car'], price:SEN.kanagawa, baby:true,
    say:'あさ 10じから あいてるよ。おやすみする へやも あるよ。',
    parent:'湯あそびひろば 葛の湯／泉区中田南5-1-16／祝日の木曜は営業', q:'葛の湯 横浜市泉区 銭湯' },
  { id:'nakajimakan', at:{'弘明寺':'🚶 あるいて 3ぷん'}, icon:'🏮', name:'{中島館|なかじまかん}', kind:'せんとう',
    open:[H(12), H(23)], rest:{dow:[5]}, restText:'きんようび',
    feat:['onsen','roten','ne','denki','car'], price:SEN.kanagawa, baby:true,
    say:'えきから すぐ！ そとの おふろが あるよ。',
    parent:'南区中島町4-75／弘明寺商店街の近く', q:'中島館 弘明寺 銭湯' },
  { id:'miurayu', at:{'弘明寺':'🚶 あるいて 12ふん'}, icon:'⚫', name:'みうら{湯|ゆ}', kind:'スーパーせんとう',
    open:[H(10), H(23)], openDow:{0:[H(10), H(24)], 6:[H(10), H(24)]}, rest:{}, restText:'おやすみ なし',
    feat:['kuro','onsen','roten','sauna'], price:'こども 350えん（どにち 450えん）／ 3さいまで ただ', baby:true,
    say:'まっくろな おゆの おんせん！ ふしぎだね。',
    parent:'黒湯天然温泉みうら湯 弘明寺店／南区中里1-25-1（京急弘明寺から徒歩約8分）／大人 平日980円・土日祝1,080円', q:'黒湯天然温泉 みうら湯 弘明寺' },
  { id:'bentenyu', at:{'伊勢佐木長者町':'🚶 あるいて 3ぷん', '関内':'🚶 あるいて 10ぷん'}, icon:'🫧', name:'{辨天湯|べんてんゆ}', kind:'せんとう',
    open:[H(15), H(23,30)], rest:{date:[10,11,20,30]}, restText:'10・11・20・30にち',
    feat:['awa'], price:SEN.kanagawa, baby:true,
    say:'おおどおり こうえんで あそんだ あとに いけるよ。',
    parent:'中区弥生町1-9（大通り公園沿い）', q:'辨天湯 横浜市中区弥生町 銭湯' },
  { id:'riseikan', at:{'伊勢佐木長者町':'🚶 あるいて 8ぷん', '阪東橋':'🚶 あるいて 8ぷん'}, icon:'♨️', name:'{利世館|りせいかん}', kind:'せんとう',
    open:[H(14), H(23,15)], rest:{date:[7,8,17,18,27,28]}, restText:'7・8・17・18・27・28にち',
    feat:['onsen','sauna','awa'], price:SEN.kanagawa, baby:true,
    say:'いせざきモールの ちかくの おんせんの せんとう。',
    parent:'中区伊勢佐木町5-127', q:'利世館 横浜 伊勢佐木町 銭湯' },
  { id:'okinayu', at:{'伊勢佐木長者町':'🚶 あるいて 6ぷん', '石川町':'🚶 あるいて 6ぷん'}, icon:'🖼️', name:'{翁湯|おきなゆ}', kind:'せんとう',
    open:[H(13), H(21)], rest:{dow:[0]}, restText:'にちようび',
    feat:['tile','bandai'], price:SEN.kanagawa, baby:true,
    say:'かべに むかしの たびの えが あるよ。よる 9じで しまるから はやめにね。',
    parent:'中区寿町4-14 寿町健康福祉交流センター2F／番台式／JR石川町駅北口から徒歩5〜6分', q:'翁湯 横浜 寿町 銭湯' },
  { id:'nakamura', at:{'伊勢佐木長者町':'🚶 あるいて 12ふん'}, icon:'🚗', name:'{中村浴場|なかむらよくじょう}', kind:'せんとう',
    open:[H(15,30), H(23)], rest:{date:[8,18,28]}, restText:'8・18・28にち',
    feat:['sauna','awa','car'], price:SEN.kanagawa, baby:true,
    say:'かぞくで くるのを まってるよ、って いってる おふろやさん。',
    parent:'南区中村町2-117-7', q:'中村浴場 横浜市南区 銭湯' },
  { id:'kinenyu', at:{'高島町':'🚶 あるいて 8ぷん'}, icon:'🎉', name:'{記念湯|きねんゆ}', kind:'せんとう',
    open:[H(15), H(23,30)], rest:{dow:[1]}, restText:'げつようび',
    feat:['many','roten','ne','utase','denki','sauna'], price:SEN.kanagawa, baby:true,
    say:'おふろの しゅるいが いっぱい！ ぜんぶ はいれるかな？',
    parent:'遊湯 記念湯／西区戸部本町45-4（京急戸部駅から徒歩1分）／祝日の月曜も休み', q:'記念湯 戸部 銭湯' },
  { id:'tanmachi', at:{'三ツ沢下町':'🚶 あるいて 15ふん', '横浜':'🚶 きたぐちから あるいて 15ふん'}, icon:'🏢', name:'{反町浴場|たんまちよくじょう}', kind:'せんとう',
    open:[H(15), H(23,30)], rest:{dow:[3]}, restText:'すいようび',
    feat:['nikai','ne','denki','sauna'], price:SEN.kanagawa, baby:true,
    say:'1かいと 2かいに おふろが ある おおきな せんとう。',
    parent:'SPA反町／神奈川区上反町1-5-2（東急反町駅から徒歩2分）／滞在2時間目安・シャンプー類は券売機で購入', q:'反町浴場 SPA反町' },
  { id:'shinmatsu', at:{'岸根公園':'🚶 あるいて 16ぷん'}, icon:'🌲', name:'{親松|しんまつ}の{湯|ゆ}', kind:'せんとう',
    open:[H(14,30), H(23)], rest:{dow:[3]}, restText:'すいようび（ほかにも おやすみ あり）',
    feat:['sauna','car'], price:SEN.kanagawa, baby:true,
    say:'きしねこうえんで あそんだ あとに いけるよ。むかしから ある おふろやさん。',
    parent:'神奈川区六角橋2-15-5（東急白楽駅から徒歩9分）／水曜のほか不定休あり', q:'親松の湯 六角橋 銭湯' },
  { id:'coco', at:{'センター北':'🚶 あるいて 5ふん'}, icon:'🛍️', name:'ゆったりCOco', kind:'スーパーせんとう',
    open:[H(10), H(23)], rest:{nth:[{dow:3, n:1}]}, restText:'まいつき さいしょの すいようび',
    feat:['onsen','roten','tanso','kazoku','car'], price:'こども 680えん（3さい〜しょうがくせい）', baby:false,
    say:'おかいものの ついでに いけるよ。3さいに なったら はいれるよ。',
    parent:'港北天然温泉ゆったりCOco／都筑区中川中央2-7-1 港北みなも3F／大人 平日1,200円・土日祝1,500円／3歳未満・オムツの子は大浴場不可（貸切家族風呂は可）／18歳未満は23時まで', q:'港北天然温泉 ゆったりCOco' },
  { id:'yukemuri', at:{'あざみ野':'🚌 むりょうの バスで いくよ'}, icon:'🚌', name:'{湯|ゆ}けむりの{里|さと}', kind:'スーパーせんとう',
    open:[H(7), H(22)], rest:{}, restText:'おみせに きいてね',
    feat:['onsen','many','tanso','roten'], price:'こども 500えん（どにち 600えん）', baby:true,
    say:'あさ 7じから あいてる！ えきから ただの バスに のっていこう。',
    parent:'天然温泉 すすき野 湯けむりの里／青葉区すすき野3-2-7／あざみ野駅西口から無料シャトル（30分おき）／大人 平日850円・土日祝980円／0歳から入浴可との紹介あり（要確認）', q:'すすき野 湯けむりの里' },

  /* ───────── けいひんとうほくせん（さいたま） ───────── */
  { id:'wakamatsu-urawa', at:{'北浦和':'🚶 にしぐちから あるいて 5ふん'}, icon:'🪵', name:'{若松湯|わかまつゆ}', kind:'せんとう',
    open:[H(15), H(23)], rest:{dow:[3]}, restText:'すいようび',
    feat:['maki'], price:SEN.saitama, baby:true,
    say:'まきを もやして おゆを わかしている、むかしながらの おふろやさん。',
    parent:'さいたま市浦和区常盤10-10-15（北浦和ふれあい通り商店街）', q:'若松湯 浦和区常盤 銭湯' },
  { id:'koraku', at:{'北浦和':'🚶 あるいて 7ふん'}, icon:'🏯', name:'{湯屋敷|ゆやしき} {孝楽|こうらく}', kind:'スーパーせんとう',
    open:[H(10), H(25)], rest:{}, restText:'おみせに きいてね',
    feat:['roten','many','sauna'], price:'こども 350えん（どにち 400えん）／ 3さいまで ただ', baby:true,
    say:'そとの おふろや どうくつの おふろが あるよ。',
    parent:'湯屋敷 孝楽／さいたま市浦和区元町2-18-12／大人 平日750円・土日祝850円／7歳以上で身長120cm以上は異性の浴室不可／サウナ・岩盤浴は中学生から', q:'湯屋敷 孝楽 北浦和' },
  { id:'inari-urawa', at:{'浦和':'🚶 にしぐちから あるいて 8ぷん'}, icon:'⛩️', name:'{稲荷湯|いなりゆ}', kind:'せんとう',
    open:[H(16), H(20,45)], rest:{dow:[1], nth:[{dow:2, n:2}]}, restText:'げつようび（2しゅうめは かようびも）',
    feat:['car'], price:SEN.saitama, baby:true,
    say:'よる 9じまえに しまるから、ゆうがたに いこうね。',
    parent:'さいたま市浦和区仲町2-18-2', q:'稲荷湯 浦和 仲町 銭湯' },
  { id:'mitake', at:{'南浦和':'🚶 にしぐちから あるいて 11ぷん'}, icon:'⛰️', name:'みたけ{湯|ゆ}', kind:'せんとう',
    open:[H(15), H(22)], rest:{dow:[1]}, restText:'げつようび',
    feat:['retro'], price:SEN.saitama, baby:true,
    say:'むかしの ままの レトロな せんとう。シャンプーは もっていこうね。',
    parent:'さいたま市南区文蔵2-24-5／シャンプー類は持参', q:'みたけ湯 南区文蔵 銭湯' },
  { id:'kamenoyu-warabi', at:{'蕨':'🚶 にしぐちから あるいて 7ふん'}, icon:'🐢', name:'{亀|かめ}の{湯|ゆ}', kind:'せんとう',
    open:[H(14,30), H(21)], rest:{dow:[3]}, restText:'すいようび',
    feat:['sauna'], price:SEN.saitama, baby:true,
    say:'かめさんの なまえの おふろやさん。おとこゆと おんなゆが ひがわりだよ。',
    parent:'蕨市北町1-8-9／閉店は21時〜22時と情報により差があるため要確認', q:'亀の湯 蕨 北町 銭湯' },
  { id:'newmatsu-kawaguchi', at:{'蕨':'🚶 にしぐちから あるいて 12ふん'}, icon:'🌲', name:'ニュー{松|まつ}の{湯|ゆ}', kind:'せんとう',
    open:[H(15), H(23,30)], openDow:{0:[H(13), H(23,30)]}, rest:{dow:[2], nth:[{dow:3, n:1}]}, restText:'かようび・さいしょの すいようび',
    feat:['roten','sauna'], price:SEN.saitama, baby:true,
    say:'そとの おふろが ある せんとう。にちようびは ひるから あいてるよ。',
    parent:'川口市芝5-21-18', q:'ニュー松の湯 川口市芝 銭湯' },
  { id:'kirakuyu-kawaguchi', at:{'川口':'🚶 あるいて 15ふん', '西川口':'🚶 あるいて 15ふん'}, icon:'😄', name:'{喜楽湯|きらくゆ}', kind:'せんとう',
    open:[H(15), H(23)], rest:{dow:[5]}, restText:'きんようび',
    feat:['sauna'], price:SEN.saitama, baby:true,
    say:'どようびと にちようびは あさも やってるよ（8じ〜12じ）。',
    parent:'川口市川口5-21-6／土日は朝風呂8:00〜12:00もあり', q:'喜楽湯 川口 銭湯' },

  /* ───────── けいひんとうほくせん（とうきょう） ───────── */
  { id:'fujinoyu-akabane', at:{'赤羽':'🚶 あるいて 15ふん'}, icon:'🌸', name:'{藤|ふじ}の{湯|ゆ}', kind:'せんとう',
    open:[H(14,30), H(23,30)], rest:{dow:[4]}, restText:'もくようび',
    feat:['yaku','sauna'], price:SEN.tokyo, baby:true,
    say:'ひがわりの くすりの おふろが あるよ。',
    parent:'北区／埼京線・京浜東北線 赤羽駅から徒歩15分', q:'藤の湯 赤羽 銭湯' },
  { id:'yanagiyu', at:{'東十条':'🚶 あるいて 5ふん'}, icon:'🌿', name:'やなぎ{湯|ゆ}', kind:'せんとう',
    open:[H(14,30), H(23)], rest:{dow:[1]}, restText:'げつようび',
    feat:['roten','tanso','silk','denki','car'], price:SEN.tokyo, baby:true,
    say:'そとの しゅわしゅわ おふろが にんき！ ぬるい おふろも あるよ。',
    parent:'北区／露天炭酸泉・ぬる湯あり／無料駐車場あり', q:'やなぎ湯 東十条 銭湯' },
  { id:'ebisuyu-oji', at:{'王子':'🚶 あるいて 3ぷん'}, icon:'🗻', name:'えびす{湯|ゆ}', kind:'せんとう',
    open:[H(15), H(24)], rest:{dow:[1]}, restText:'げつようび',
    feat:['penki','bandai','maki','car'], price:SEN.tokyo, baby:true,
    say:'かべに おおきな ふじさんの え！ あすかやま こうえんの ちかくだよ。',
    parent:'北区／番台式／井戸水を薪で沸かす／ペンキ絵あり', q:'えびす湯 王子 銭湯' },
  { id:'cocofuro-kaga', at:{'王子':'🚶 あるいて 8ぷん'}, icon:'🌅', name:'COCOFURO かが{浴場|よくじょう}', kind:'せんとう',
    open:[H(6), H(24)], rest:{nth:[{dow:2, n:3, months:[3,5,9,11]}]}, restText:'3・5・9・11がつの 3しゅうめの かようび',
    feat:['asa','yaku','sauna'], price:SEN.tokyo, baby:true,
    say:'あさ 6じから あいてる あたらしい せんとう。',
    parent:'COCOFURO（ココフロ）かが浴場／北区／2023年オープン', q:'COCOFURO かが浴場 王子' },
  { id:'daikokuyu-kaminakazato', at:{'上中里':'🚶 あるいて 2ふん'}, icon:'🏠', name:'{大黒湯|だいこくゆ}', kind:'せんとう',
    open:[H(15), H(23)], rest:{dow:[2]}, restText:'かようび',
    feat:['roten','yaku','sauna','car'], price:SEN.tokyo, baby:true,
    say:'えきから すぐ！ アットホームな おふろやさん。',
    parent:'北区／日替わり薬湯／無料駐車場あり', q:'大黒湯 上中里 銭湯' },
  { id:'chitoseyu', at:{'西日暮里':'🚶 あるいて 5ふん', '田端':'🚶 あるいて 5ふん'}, icon:'🗻', name:'{千歳湯|ちとせゆ}', kind:'せんとう',
    open:[H(15,30), H(24)], rest:{dow:[5]}, restText:'きんようび',
    feat:['penki','yaku','retro'], price:SEN.tokyo, baby:true,
    say:'ふじさんの えと ひがわりの くすりの おふろ。レトロだよ。',
    parent:'荒川区／井戸水使用／手ぶらセットあり', q:'千歳湯 西日暮里 銭湯' },
  { id:'saitoyu', at:{'日暮里':'🚶 あるいて 3ぷん'}, icon:'🫧', name:'{日暮里|にっぽり} {斉藤湯|さいとうゆ}', kind:'せんとう',
    open:[H(14), H(23)], rest:{dow:[5]}, restText:'きんようび',
    feat:['roten','tanso','silk','denki'], price:SEN.tokyo, baby:true,
    say:'おふろも シャワーも やわらかい おみず。そとの いわぶろも あるよ。',
    parent:'荒川区／全て軟水／露天岩風呂（シルキー風呂）・炭酸泉', q:'日暮里 斉藤湯' },
  { id:'koganeyu-nippori', at:{'日暮里':'🚶 あるいて 7ふん'}, icon:'✨', name:'{黄金湯|こがねゆ}', kind:'せんとう',
    open:[H(15), H(23)], rest:{dow:[2]}, restText:'かようび',
    feat:['sauna'], price:SEN.tokyo, baby:true,
    say:'つよい ジェットの おふろが じまん。',
    parent:'荒川区', q:'黄金湯 日暮里 銭湯' },
  { id:'tsubameyu', at:{'御徒町':'🚶 あるいて 4ぷん'}, icon:'🐦', name:'{燕湯|つばめゆ}', kind:'せんとう',
    open:[H(6), H(20)], rest:{dow:[1,2]}, restText:'げつようび・かようび',
    feat:['asa','bandai','yaku'], price:SEN.tokyo, baby:true,
    say:'あさ 6じから やってる！ うえのの どうぶつえんの かえりにも いけるよ。',
    parent:'台東区／番台式／毎日朝湯／日曜は薬湯', q:'燕湯 御徒町 銭湯' },
  { id:'inariyu-kanda', at:{'神田':'🚶 あるいて 6ぷん'}, icon:'🎨', name:'{稲荷湯|いなりゆ}', kind:'せんとう',
    open:[H(14,40), H(22,30)], rest:{dow:[0]}, restText:'にちようび',
    feat:['penki'], price:SEN.tokyo, baby:true,
    say:'まいとし かきかえる かべの えが みどころ。',
    parent:'稲荷湯（神田）／千代田区／ペンキ絵は年1回描きかえ', q:'稲荷湯 神田 銭湯' },
  { id:'konparuyu', at:{'新橋':'🚶 あるいて 4ぷん'}, icon:'⛩️', name:'{金春湯|こんぱるゆ}', kind:'せんとう',
    open:[H(14), H(22)], openDow:{6:[H(14), H(20)]}, rest:{dow:[0]}, restText:'にちようび・しゅくじつ',
    feat:['bandai','tile','penki'], price:SEN.tokyo, baby:true,
    say:'ぎんざの ちかくの むかしからの せんとう。おおきな かみだなが あるよ。',
    parent:'中央区（銀座八丁目）／番台式／九谷焼のタイル絵／祝日も休み', q:'金春湯 新橋 銭湯' },
  { id:'fureainoyu', at:{'浜松町':'🚶 あるいて 5ふん'}, icon:'🤝', name:'ふれあいの{湯|ゆ}', kind:'せんとう',
    open:[H(15), H(23)], openDow:{0:[H(14), H(23)]}, rest:{dow:[1]}, restText:'げつようび',
    feat:['rest'], price:SEN.tokyo, baby:true,
    say:'あがった あとに やすむ へやが あるよ。',
    parent:'港区／休憩室あり／ドライヤー無料', q:'ふれあいの湯 浜松町 銭湯' },
  { id:'suehiroyu', at:{'大井町':'🚶 あるいて 4ぷん'}, icon:'⬡', name:'すえひろ{湯|ゆ}', kind:'せんとう',
    open:[H(15), H(25)], openDow:{0:[H(10), H(25)], 6:[H(10), H(25)]}, rest:{}, restText:'おやすみ なし',
    feat:['ne','denki','sauna'], price:SEN.tokyo, baby:true,
    say:'はっかっけいの めずらしい あらいば！ どにちは あさ 10じから。',
    parent:'品川区／定休日なし／土日祝は10時から', q:'すえひろ湯 大井町 銭湯' },
  { id:'tokyoyokujo', at:{'大井町':'🚶 あるいて 7ふん'}, icon:'🎏', name:'{東京浴場|とうきょうよくじょう}', kind:'せんとう',
    open:[H(15), H(22)], rest:{dow:[1]}, restText:'げつようび',
    feat:['niwa','yaku'], price:SEN.tokyo, baby:true,
    say:'おにわに こいの いけが ある、おてらみたいな たてもの！',
    parent:'品川区／宮造り・中庭に鯉の池', q:'東京浴場 大井町 銭湯' },
  { id:'suijinyu', at:{'大森':'🚶 あるいて 6ぷん'}, icon:'💧', name:'{水神湯|すいじんゆ}', kind:'せんとう',
    open:[H(15), H(22)], rest:{dow:[1], until:'2026-10-15'}, restText:'げつようび（10がつ15にちまで こうじで おやすみ）',
    feat:['retro'], price:SEN.tokyo, baby:true,
    say:'からだの しんまで あったまる、やわらかい おゆ。',
    parent:'品川区／2026年10月5日〜15日は改修工事のため休業', q:'水神湯 大森 銭湯' },
  { id:'yucity-kamata', at:{'蒲田':'🚶 あるいて 5ふん'}, icon:'⚫', name:'ゆ〜シティー{蒲田|かまた}', kind:'せんとう',
    open:[H(11), H(24)], rest:{dow:[2]}, restText:'かようび',
    feat:['kuro','onsen','roten','sauna','car'], price:SEN.tokyo, baby:true,
    say:'まっくろな おんせんの そとの おふろ！ ひるから あいてるよ。',
    parent:'大田区／天然黒湯温泉／無料駐車場あり', q:'ゆ〜シティー蒲田' },
  { id:'kaiseiyu', at:{'蒲田':'🚶 あるいて 7ふん'}, icon:'⚫', name:'{改正湯|かいせいゆ}', kind:'せんとう',
    open:[H(15), H(23,30)], rest:{dow:[5]}, restText:'きんようび',
    feat:['kuro','onsen','tanso','silk','car'], price:SEN.tokyo, baby:true,
    say:'くろい おんせんの しゅわしゅわ おふろ。ちいさい こ づれでも あんしん。',
    parent:'大田区／黒湯天然温泉・黒湯炭酸泉／バリアフリー対応', q:'改正湯 蒲田 銭湯' },

  /* ───────── けいひんとうほくせん・ねぎしせん（かながわ） ───────── */
  { id:'masanoyu', at:{'川崎':'🚶 あるいて 5ふん'}, icon:'♨️', name:'{政之湯|まさのゆ}', kind:'せんとう',
    open:[H(14), H(24)], rest:{date:[6,16,26]}, restText:'6・16・26にち',
    feat:['onsen','yaku','sauna'], price:SEN.kanagawa, baby:true,
    say:'かわさきえきの ちかくの おんせんの せんとう。',
    parent:'川崎市川崎区南町2-4（ビル1階）／天然温泉', q:'政之湯 川崎 銭湯' },
  { id:'kichinoyu', at:{'川崎':'🚶 ひがしぐちから あるいて 13ぷん'}, icon:'🧑‍🦳', name:'{吉|きち}の{湯|ゆ}', kind:'せんとう',
    open:[H(14,40), H(23)], rest:{dow:[6]}, restText:'どようび',
    feat:['bandai','retro'], price:SEN.kanagawa, baby:true,
    say:'ばんだいの ある むかしながらの おふろやさん。',
    parent:'川崎市川崎区貝塚2-5-8／番台式／休業日は公式Xで告知', q:'吉の湯 川崎区貝塚 銭湯' },
  { id:'ushiodayu', at:{'鶴見':'🚶 あるいて 10ぷん'}, icon:'🌱', name:'{潮田湯|うしおだゆ}', kind:'せんとう',
    open:[H(15), H(23)], rest:{dow:[5]}, restText:'きんようび',
    feat:['car'], price:SEN.kanagawa, baby:true,
    say:'おとこゆからは みどりの おんしつが みえるよ。',
    parent:'鶴見区本町通2-50（京急鶴見駅から徒歩8分）／駐車場5台', q:'潮田湯 鶴見 銭湯' },
  { id:'washinoyu', at:{'新子安':'🚶 あるいて 7ふん'}, icon:'🪨', name:'{鷲|わし}の{湯|ゆ}', kind:'せんとう',
    open:[H(11), H(24)], rest:{}, restText:'ときどき（おみせに きいてね）',
    feat:['onsen','car'], price:SEN.kanagawa, baby:true,
    say:'あきたけんの めずらしい いしの おふろが あるよ。',
    parent:'神奈川区七島町151（京急子安駅から徒歩4分）／北投石の湯／駐車場50台／不定休', q:'鷲の湯 子安 銭湯' },
  { id:'tokunoyu', at:{'東神奈川':'🚶 あるいて 10ぷん'}, icon:'🌳', name:'{徳|とく}の{湯|ゆ}', kind:'せんとう',
    open:[H(11), H(23)], openDow:{0:[H(9), H(23)]}, rest:{dow:[4]}, restText:'もくようび',
    feat:['roten'], price:SEN.kanagawa, baby:true,
    say:'そとの おふろが ある せんとう。ひるまから あいてるよ。',
    parent:'神奈川区西神奈川2-1-5（東急東横線 東白楽駅西口すぐ）／日祝は9時から', q:'徳の湯 東白楽 銭湯' },
  { id:'skyspa', at:{'横浜':'🚶 ひがしぐちから ちかで すぐ'}, icon:'🏙️', name:'スカイスパYOKOHAMA', kind:'スパ', adult:'ちゅうがくせいから',
    open:[H(0), H(24)], rest:{}, restText:'おやすみ なし（あさ そうじの じかん あり）',
    feat:['sauna'], price:'こどもは はいれません', baby:false,
    say:'おとなの ための おふろ。おおきく なったら いってみよう。',
    parent:'西区高島2-19-12 横浜スカイビル14F／中学生未満は利用不可／平日2,600円〜・休日3,300円〜', q:'スカイスパYOKOHAMA' },
  { id:'spaeas', at:{'横浜':'🚶 にしぐちから あるいて 5ふん'}, icon:'🪨', name:'SPA EAS', kind:'スパ', adult:'16さいから',
    open:[H(9,30), H(23)], rest:{}, restText:'おやすみ なし（てんけんの ひ あり）',
    feat:['onsen','roten','sauna'], price:'こどもは はいれません', baby:false,
    say:'おとなの ための おんせん。おおきく なったら いってみよう。',
    parent:'横浜天然温泉 SPA EAS／西区北幸2-2-1／16歳未満は利用不可／平日4,400円・土日祝5,200円／現金不可', q:'横浜天然温泉 SPA EAS' },
  { id:'manyo', at:{'桜木町':'🚶 あるいて 15ふん', '横浜':'🚌 にしぐちから むりょうの バス'}, icon:'🌉', name:'{万葉倶楽部|まんようくらぶ}', kind:'おんせん',
    open:[H(0), H(24)], rest:{}, restText:'おやすみ なし',
    feat:['onsen','ashiyu','many'], price:'しょうがくせい 1,500えん／ ようじ 1,800えん（たかめ）', baby:true,
    say:'おくじょうの あしゆから みなとみらいの よるの けしきが みえるよ。',
    parent:'横浜みなとみらい万葉倶楽部／中区新港2-7-1／横浜駅西口から無料シャトル／大人3,500円＋入湯税／24時間営業', q:'横浜みなとみらい 万葉倶楽部' },
  { id:'ebisuonsen', at:{'石川町':'🚶 あるいて 3ぷん'}, icon:'🏮', name:'{恵|え}びす{温泉|おんせん}', kind:'せんとう',
    open:[H(11), H(25)], rest:{dow:[2]}, restText:'かようび',
    feat:['many','sauna','yaku','car'], price:SEN.kanagawa, baby:true,
    say:'ちゅうかがいの すぐ ちかく！ いろんな おふろが あるよ。',
    parent:'中区山下町161／ラドン温泉・歩行浴・ミスト風呂', q:'恵びす温泉 石川町 銭湯' },
  { id:'koyamayu', at:{'石川町':'🚶 もとまちぐちから あるいて 3ぷん'}, icon:'⛰️', name:'{小山湯|こやまゆ}', kind:'せんとう',
    open:[H(9,30), H(21)], rest:{dow:[4,5]}, restText:'もくようび・きんようび',
    feat:['asa','yaku','car'], price:SEN.kanagawa, baby:true,
    say:'あさ 9じはんから あいてる！ もとまちの おかいものの あとに。',
    parent:'中区石川町3-106-4／駐車場5台', q:'小山湯 石川町 銭湯' },
  { id:'inariyu-yamate', at:{'山手':'🚶 あるいて 5ふん'}, icon:'🦊', name:'いなり{湯|ゆ}', kind:'せんとう',
    open:[H(15), H(23,30)], rest:{dow:[2]}, restText:'かようび',
    feat:['onsen','bandai','retro','denki'], price:SEN.kanagawa, baby:true,
    say:'ばんだいの ある しょうわの おふろやさん。おんせんだよ。',
    parent:'中区大和町1-12／番台式／天然温泉', q:'いなり湯 山手 銭湯' },
  { id:'dai2kouyou', at:{'根岸':'🚶 あるいて 12ふん'}, icon:'🌊', name:'{第二江陽館|だいにこうようかん}', kind:'せんとう',
    open:[H(14,10), H(23)], rest:{dow:[2]}, restText:'かようび',
    feat:['yaku','sauna','car'], price:SEN.kanagawa, baby:true,
    say:'ひがわりの くすりの おふろ。マンモスプールの ちかくだよ。',
    parent:'磯子区中浜町4-16／駐車場4台', q:'第二江陽館 磯子 銭湯' },
  { id:'taiseikan', at:{'根岸':'🚶 あるいて 16ぷん'}, icon:'🫧', name:'ねぎしの{湯|ゆ} {大盛舘|たいせいかん}', kind:'せんとう',
    open:[H(14), H(25)], rest:{dow:[2]}, restText:'かようび',
    feat:['roten','tanso','car'], price:SEN.kanagawa, baby:true,
    say:'そとの しゅわしゅわ おふろが にんき！',
    parent:'磯子区上町5-13／露天炭酸泉／駐車場あり／バスなら「根岸橋」下車徒歩2分', q:'ねぎしの湯 大盛舘' },
  { id:'ousama-konandai', at:{'港南台':'🚌 バスで 15ふん（「ひの」で おりる）'}, icon:'👑', name:'おふろの{王様|おうさま}', kind:'スーパーせんとう',
    open:[H(9), H(24)], rest:{}, restText:'おやすみ なし',
    feat:['onsen','roten','many'], price:'しょうがくせい 350えん／ ちいさい こ ただ', baby:true,
    say:'たけやぶの なかの そとの おふろが じまん！',
    parent:'おふろの王様 港南台店／港南区日野中央2-45-7／港南台駅から神奈中バス約15分「日野」下車', q:'おふろの王様 港南台店' },
  { id:'taya', at:{'本郷台':'🚌 むりょうの バスで いくよ'}, icon:'🍃', name:'{湯快爽快|ゆかいそうかい} たや', kind:'スーパーせんとう',
    open:[H(10), H(24)], rest:{}, restText:'てんけんの ひ（おみせに きいてね）',
    feat:['onsen','roten','many'], price:'こども 350えん（3さい〜しょうがくせい）／ 2さいまで ただ', baby:true,
    say:'えきから ただの バスで いける おんせん。かようびは こどもが やすいよ。',
    parent:'野天湯元 湯快爽快 たや／栄区田谷町146-3／本郷台駅から無料シャトル／火曜はキッズデー（小学生以下300円）／2026年10月15日から小学生以下だけの入館不可／オムツの子は浴槽不可', q:'野天湯元 湯快爽快 たや' },
  { id:'hibariyu', at:{'大船':'🚶 ひがしぐちから あるいて 3ぷん'}, icon:'🐤', name:'ひばり{湯|ゆ}', kind:'せんとう',
    open:[H(13), H(23)], openDow:{0:[H(10,30), H(23)], 6:[H(10,30), H(23)]}, rest:{dow:[3], nth:[{dow:4, n:3}]}, restText:'すいようび・3しゅうめの もくようび',
    feat:['tanso','ne','denki','sauna'], price:SEN.kanagawa, baby:true,
    say:'しゅわしゅわの おふろが にんき。かまくらの おでかけの あとに。',
    parent:'鎌倉市大船1-13-7（大船仲通り商店街付近）／土日は10:30から', q:'ひばり湯 大船 銭湯' }
];

const FEATURES = {
  roten: '🌳 そとの おふろ', onsen: '♨️ おんせん', sauna: '🔥 サウナ', denki: '⚡ でんきぶろ',
  ne: '🛌 ねころぶ おふろ', utase: '🚿 うたせゆ', awa: '🫧 あわぶろ', kuro: '⚫ くろい おゆ',
  kazoku: '👨‍👩‍👧 かぞくぶろ', car: '🚗 ちゅうしゃじょう', tile: '🖼️ タイルの え', many: '🎉 おふろ いっぱい',
  tanso: '🫧 しゅわしゅわ おふろ', nikai: '🏢 2かいだて', maki: '🪵 まきで わかす', penki: '🗻 ふじさんの え',
  bandai: '🧑‍🦳 ばんだい', yaku: '🌿 くすりの おふろ', asa: '🌅 あさから', retro: '📻 レトロ',
  silk: '🥛 シルクぶろ', niwa: '🎏 こいの いけ', rest: '🛋️ やすむ へや', ashiyu: '🦶 あしゆ'
};
