// でんしゃで おふろやさん — データ
// {漢字|よみ} は ふりがな つきで ひょうじ される。
// at   : { えきめい: 'えきからの いきかた' } … おなじ おふろを いくつかの えきに だせる
// open : [あく ふん, しまる ふん]（24じ いこうは 1440 より おおきい かず）
// openDow : ようびごとの じかん { 0:にちようび … 6:どようび }
// rest : dow=ようび / date=ひにち / nth=[{dow,n,months}] だい n ○ようび / until=この ひまで おやすみ

const SEN = {
  tokyo:    'こども 200えん（6〜11さい）／ ちいさい こ 100えん',
  saitama:  'こども 200えん（6〜11さい）／ ちいさい こ 100えん',
  kanagawa: 'こども 250えん（6〜11さい）／ ちいさい こ 130えん'
};

const LINES = [
  {
    id: 'blue', name: 'ブルーライン', sub: 'よこはま しえい ちかてつ', color: '#0b78be',
    stations: [
      '{湘南台|しょうなんだい}', '{下飯田|しもいいだ}', '{立場|たてば}', '{中田|なかだ}', '{踊場|おどりば}',
      '{戸塚|とつか}', '{舞岡|まいおか}', '{下永谷|しもながや}', '{上永谷|かみながや}', '{港南中央|こうなんちゅうおう}',
      '{上大岡|かみおおおか}', '{弘明寺|ぐみょうじ}', '{蒔田|まいた}', '{吉野町|よしのちょう}', '{阪東橋|ばんどうばし}',
      '{伊勢佐木長者町|いせざきちょうじゃまち}', '{関内|かんない}', '{桜木町|さくらぎちょう}', '{高島町|たかしまちょう}', '{横浜|よこはま}',
      '{三ツ沢下町|みつざわしもちょう}', '{三ツ沢上町|みつざわかみちょう}', '{片倉町|かたくらちょう}', '{岸根公園|きしねこうえん}', '{新横浜|しんよこはま}',
      '{北新横浜|きたしんよこはま}', '{新羽|にっぱ}', '{仲町台|なかまちだい}', 'センター{南|みなみ}', 'センター{北|きた}',
      '{中川|なかがわ}', 'あざみ{野|の}'
    ]
  },
  {
    id: 'keihin', name: 'けいひんとうほく・ねぎしせん', sub: 'JR', color: '#00a7db',
    stations: [
      { sep: 'さいたまけん' },
      '{大宮|おおみや}', 'さいたま{新都心|しんとしん}', '{与野|よの}', '{北浦和|きたうらわ}', '{浦和|うらわ}',
      '{南浦和|みなみうらわ}', '{蕨|わらび}', '{西川口|にしかわぐち}', '{川口|かわぐち}',
      { sep: 'とうきょうと' },
      '{赤羽|あかばね}', '{東十条|ひがしじゅうじょう}', '{王子|おうじ}', '{上中里|かみなかざと}', '{田端|たばた}',
      '{西日暮里|にしにっぽり}', '{日暮里|にっぽり}', '{鶯谷|うぐいすだに}', '{上野|うえの}', '{御徒町|おかちまち}',
      '{秋葉原|あきはばら}', '{神田|かんだ}', '{東京|とうきょう}', '{有楽町|ゆうらくちょう}', '{新橋|しんばし}',
      '{浜松町|はままつちょう}', '{田町|たまち}', '{高輪|たかなわ}ゲートウェイ', '{品川|しながわ}', '{大井町|おおいまち}',
      '{大森|おおもり}', '{蒲田|かまた}',
      { sep: 'かながわけん' },
      '{川崎|かわさき}', '{鶴見|つるみ}', '{新子安|しんこやす}', '{東神奈川|ひがしかながわ}', '{横浜|よこはま}',
      '{桜木町|さくらぎちょう}', '{関内|かんない}', '{石川町|いしかわちょう}', '{山手|やまて}', '{根岸|ねぎし}',
      '{磯子|いそご}', '{新杉田|しんすぎた}', '{洋光台|ようこうだい}', '{港南台|こうなんだい}', '{本郷台|ほんごうだい}',
      '{大船|おおふな}'
    ]
  },
  {
    id: 'toyoko', name: 'とうよこせん', sub: 'とうきゅう', color: '#da0442',
    stations: [
      { sep: 'とうきょうと' },
      '{渋谷|しぶや}', '{代官山|だいかんやま}', '{中目黒|なかめぐろ}', '{祐天寺|ゆうてんじ}', '{学芸大学|がくげいだいがく}',
      '{都立大学|とりつだいがく}', '{自由|じゆう}が{丘|おか}', '{田園調布|でんえんちょうふ}', '{多摩川|たまがわ}',
      { sep: 'かながわけん' },
      '{新丸子|しんまるこ}', '{武蔵小杉|むさしこすぎ}', '{元住吉|もとすみよし}', '{日吉|ひよし}', '{綱島|つなしま}',
      '{大倉山|おおくらやま}', '{菊名|きくな}', '{妙蓮寺|みょうれんじ}', '{白楽|はくらく}', '{東白楽|ひがしはくらく}',
      '{反町|たんまち}', '{横浜|よこはま}'
    ]
  },
  {
    id: 'sotetsu', name: 'そうてつせん', sub: 'そうてつ', color: '#1b3c8c',
    stations: [
      { sep: 'ほんせん' },
      '{横浜|よこはま}', '{平沼橋|ひらぬまばし}', '{西横浜|にしよこはま}', '{天王町|てんのうちょう}', '{星川|ほしかわ}',
      '{和田町|わだまち}', '{上星川|かみほしかわ}', '{西谷|にしや}', '{鶴|つる}ヶ{峰|みね}', '{二俣川|ふたまたがわ}',
      '{希望|きぼう}ヶ{丘|おか}', '{三|み}ツ{境|きょう}', '{瀬谷|せや}', '{大和|やまと}', '{相模大塚|さがみおおつか}',
      'さがみ{野|の}', 'かしわ{台|だい}', '{海老名|えびな}',
      { sep: 'いずみのせん（ふたまたがわ から）' },
      '{南万騎|みなみまき}が{原|はら}', '{緑園都市|りょくえんとし}', '{弥生台|やよいだい}', 'いずみ{野|の}', 'いずみ{中央|ちゅうおう}',
      'ゆめが{丘|おか}', '{湘南台|しょうなんだい}',
      { sep: 'しんよこはません（にしや から）' },
      '{羽沢横浜国大|はざわよこはまこくだい}', '{新横浜|しんよこはま}'
    ]
  },
  {
    id: 'keikyu', name: 'けいきゅうせん', sub: 'けいきゅう', color: '#e60012',
    stations: [
      { sep: 'ほんせん（とうきょうと）' },
      '{泉岳寺|せんがくじ}', '{品川|しながわ}', '{北品川|きたしながわ}', '{新馬場|しんばんば}', '{青物横丁|あおものよこちょう}',
      '{鮫洲|さめず}', '{立会川|たちあいがわ}', '{大森海岸|おおもりかいがん}', '{平和島|へいわじま}', '{大森町|おおもりまち}',
      '{梅屋敷|うめやしき}', '{京急蒲田|けいきゅうかまた}', '{雑色|ぞうしき}', '{六郷土手|ろくごうどて}',
      { sep: 'ほんせん（かながわけん）' },
      '{京急川崎|けいきゅうかわさき}', '{八丁畷|はっちょうなわて}', '{鶴見市場|つるみいちば}', '{京急鶴見|けいきゅうつるみ}', '{花月総持寺|かげつそうじじ}',
      '{生麦|なまむぎ}', '{京急新子安|けいきゅうしんこやす}', '{子安|こやす}', '{神奈川新町|かながわしんまち}', '{京急東神奈川|けいきゅうひがしかながわ}',
      '{神奈川|かながわ}', '{横浜|よこはま}', '{戸部|とべ}', '{日ノ出町|ひのでちょう}', '{黄金町|こがねちょう}',
      '{南太田|みなみおおた}', '{井土|いど}ヶ{谷|や}', '{弘明寺|ぐみょうじ}', '{上大岡|かみおおおか}', '{屏風浦|びょうぶがうら}',
      '{杉田|すぎた}', '{京急富岡|けいきゅうとみおか}', '{能見台|のうけんだい}', '{金沢文庫|かなざわぶんこ}', '{金沢八景|かなざわはっけい}',
      '{追浜|おっぱま}', '{京急田浦|けいきゅうたうら}', '{安針塚|あんじんづか}', '{逸見|へみ}', '{汐入|しおいり}',
      '{横須賀中央|よこすかちゅうおう}', '{県立大学|けんりつだいがく}', '{堀|ほり}ノ{内|うち}', '{京急大津|けいきゅうおおつ}', '{馬堀海岸|まぼりかいがん}',
      '{浦賀|うらが}',
      { sep: 'くうこうせん（けいきゅうかまた から）' },
      '{糀谷|こうじや}', '{大鳥居|おおとりい}', '{穴守稲荷|あなもりいなり}', '{天空橋|てんくうばし}',
      '{羽田空港|はねだくうこう}{第|だい}3ターミナル', '{羽田空港|はねだくうこう}{第|だい}1・{第|だい}2ターミナル',
      { sep: 'だいしせん（けいきゅうかわさき から）' },
      '{港町|みなとちょう}', '{鈴木町|すずきちょう}', '{川崎大師|かわさきだいし}', '{東門前|ひがしもんぜん}', '{大師橋|だいしばし}', '{小島新田|こじましんでん}',
      { sep: 'ずしせん（かなざわはっけい から）' },
      '{六浦|むつうら}', '{神武寺|じんむじ}', '{逗子|ずし}・{葉山|はやま}',
      { sep: 'くりはません（ほりのうち から）' },
      '{新大津|しんおおつ}', '{北久里浜|きたくりはま}', '{京急久里浜|けいきゅうくりはま}', 'YRP{野比|のび}', '{京急長沢|けいきゅうながさわ}',
      '{津久井浜|つくいはま}', '{三浦海岸|みうらかいがん}', '{三崎口|みさきぐち}'
    ]
  },
  {
    id: 'asakusa', name: 'とえい あさくさせん', sub: 'とえい ちかてつ', color: '#e85298',
    stations: [
      '{西馬込|にしまごめ}', '{馬込|まごめ}', '{中延|なかのぶ}', '{戸越|とごし}', '{五反田|ごたんだ}',
      '{高輪台|たかなわだい}', '{泉岳寺|せんがくじ}', '{三田|みた}', '{大門|だいもん}', '{新橋|しんばし}',
      '{東銀座|ひがしぎんざ}', '{宝町|たからちょう}', '{日本橋|にほんばし}', '{人形町|にんぎょうちょう}', '{東日本橋|ひがしにほんばし}',
      '{浅草橋|あさくさばし}', '{蔵前|くらまえ}', '{浅草|あさくさ}', '{本所吾妻橋|ほんじょあづまばし}', '{押上|おしあげ}'
    ]
  }
];

const H = (h, m = 0) => h * 60 + m;

const BATHS = [
  /* ───────── ブルーライン ───────── */
  { id:'kuzunoyu', at:{'踊場':'🚶 あるいて 10ぷん'}, icon:'🌳', name:'{葛|くず}の{湯|ゆ}', kind:'せんとう',
    open:[H(10), H(24)], rest:{dow:[4]}, restText:'もくようび',
    feat:['onsen','roten','utase','sauna','car'], price:SEN.kanagawa, baby:true,
    say:'あさ 10じから あいてるよ。おやすみする へやも あるよ。',
    parent:'湯あそびひろば 葛の湯／泉区中田南5-1-16／祝日の木曜は営業', q:'葛の湯 横浜市泉区 銭湯' },
  { id:'nakajimakan', at:{'弘明寺':'🚶 あるいて 3ぷん', 'keikyu:弘明寺':'🚶 あるいて 8ぷん'}, icon:'🏮', name:'{中島館|なかじまかん}', kind:'せんとう',
    open:[H(12), H(23)], rest:{dow:[5]}, restText:'きんようび',
    feat:['onsen','roten','ne','denki','car'], price:SEN.kanagawa, baby:true,
    say:'えきから すぐ！ そとの おふろが あるよ。',
    parent:'南区中島町4-75／弘明寺商店街の近く', q:'中島館 弘明寺 銭湯' },
  { id:'miurayu', at:{'弘明寺':'🚶 あるいて 12ふん', 'keikyu:弘明寺':'🚶 あるいて 8ぷん'}, icon:'⚫', name:'みうら{湯|ゆ}', kind:'スーパーせんとう',
    open:[H(10), H(23)], openDow:{0:[H(10), H(24)], 6:[H(10), H(24)]}, rest:{}, restText:'おやすみ なし',
    feat:['kuro','onsen','roten','sauna'], price:'こども 350えん（どにち 450えん）／ 3さいまで ただ', baby:true,
    say:'まっくろな おゆの おんせん！ ふしぎだね。',
    parent:'黒湯天然温泉みうら湯 弘明寺店／南区中里1-25-1（京急弘明寺から徒歩約8分）／大人 平日980円・土日祝1,080円', q:'黒湯天然温泉 みうら湯 弘明寺' },
  { id:'bentenyu', at:{'伊勢佐木長者町':'🚶 あるいて 3ぷん', '関内':'🚶 あるいて 10ぷん'}, icon:'🫧', name:'{辨天湯|べんてんゆ}', kind:'せんとう',
    open:[H(15), H(23,30)], rest:{date:[10,11,20,30]}, restText:'10・11・20・30にち',
    feat:['awa'], price:SEN.kanagawa, baby:true,
    say:'おおどおり こうえんで あそんだ あとに いけるよ。',
    parent:'中区弥生町1-9（大通り公園沿い）', q:'辨天湯 横浜市中区弥生町 銭湯' },
  { id:'riseikan', at:{'伊勢佐木長者町':'🚶 あるいて 8ぷん', '阪東橋':'🚶 あるいて 8ぷん', '日ノ出町':'🚶 あるいて 8ぷん', '黄金町':'🚶 あるいて 8ぷん'}, icon:'♨️', name:'{利世館|りせいかん}', kind:'せんとう',
    open:[H(14), H(23,15)], rest:{date:[7,8,17,18,27,28]}, restText:'7・8・17・18・27・28にち',
    feat:['onsen','sauna','awa'], price:SEN.kanagawa, baby:true,
    say:'いせざきモールの ちかくの おんせんの せんとう。',
    parent:'中区伊勢佐木町5-127', q:'利世館 横浜 伊勢佐木町 銭湯' },
  { id:'okinayu', at:{'伊勢佐木長者町':'🚶 あるいて 6ぷん', '石川町':'🚶 あるいて 6ぷん'}, icon:'🖼️', name:'{翁湯|おきなゆ}', kind:'せんとう',
    open:[H(13), H(21)], rest:{dow:[0]}, restText:'にちようび',
    feat:['tile','bandai'], price:SEN.kanagawa, baby:true,
    say:'かべに むかしの たびの えが あるよ。よる 9じで しまるから はやめにね。',
    parent:'中区寿町4-14 寿町健康福祉交流センター2F／番台式／JR石川町駅北口から徒歩5〜6分', q:'翁湯 横浜 寿町 銭湯' },
  { id:'nakamura', at:{'伊勢佐木長者町':'🚶 あるいて 12ふん'}, icon:'🚗', name:'{中村浴場|なかむらよくじょう}', kind:'せんとう',
    open:[H(15,30), H(23)], rest:{date:[8,18,28]}, restText:'8・18・28にち',
    feat:['sauna','awa','car'], price:SEN.kanagawa, baby:true,
    say:'かぞくで くるのを まってるよ、って いってる おふろやさん。',
    parent:'南区中村町2-117-7', q:'中村浴場 横浜市南区 銭湯' },
  { id:'kinenyu', at:{'高島町':'🚶 あるいて 8ぷん', '平沼橋':'🚶 あるいて 8ぷん', '戸部':'🚶 あるいて 1ぷん'}, icon:'🎉', name:'{記念湯|きねんゆ}', kind:'せんとう',
    open:[H(15), H(23,30)], rest:{dow:[1]}, restText:'げつようび',
    feat:['many','roten','ne','utase','denki','sauna'], price:SEN.kanagawa, baby:true,
    say:'おふろの しゅるいが いっぱい！ ぜんぶ はいれるかな？',
    parent:'遊湯 記念湯／西区戸部本町45-4（京急戸部駅から徒歩1分）／祝日の月曜も休み', q:'記念湯 戸部 銭湯' },
  { id:'tanmachi', at:{'三ツ沢下町':'🚶 あるいて 15ふん', '横浜':'🚶 きたぐちから あるいて 15ふん', '反町':'🚶 あるいて 2ふん', '神奈川':'🚶 あるいて 10ぷん'}, icon:'🏢', name:'{反町浴場|たんまちよくじょう}', kind:'せんとう',
    open:[H(15), H(23,30)], rest:{dow:[3]}, restText:'すいようび',
    feat:['nikai','ne','denki','sauna'], price:SEN.kanagawa, baby:true,
    say:'1かいと 2かいに おふろが ある おおきな せんとう。',
    parent:'SPA反町／神奈川区上反町1-5-2（東急反町駅から徒歩2分）／滞在2時間目安・シャンプー類は券売機で購入', q:'反町浴場 SPA反町' },
  { id:'shinmatsu', at:{'岸根公園':'🚶 あるいて 16ぷん', '白楽':'🚶 あるいて 9ふん'}, icon:'🌲', name:'{親松|しんまつ}の{湯|ゆ}', kind:'せんとう',
    open:[H(14,30), H(23)], rest:{dow:[3]}, restText:'すいようび（ほかにも おやすみ あり）',
    feat:['sauna','car'], price:SEN.kanagawa, baby:true,
    say:'きしねこうえんで あそんだ あとに いけるよ。むかしから ある おふろやさん。',
    parent:'神奈川区六角橋2-15-5（東急白楽駅から徒歩9分）／水曜のほか不定休あり', q:'親松の湯 六角橋 銭湯' },
  { id:'coco', at:{'センター北':'🚶 あるいて 5ふん'}, icon:'🛍️', name:'ゆったりCOco', kind:'スーパーせんとう',
    open:[H(10), H(23)], rest:{nth:[{dow:3, n:1}]}, restText:'まいつき さいしょの すいようび',
    feat:['onsen','roten','tanso','kazoku','car'], price:'こども 680えん（3さい〜しょうがくせい）', baby:false,
    say:'おかいものの ついでに いけるよ。3さいに なったら はいれるよ。',
    parent:'港北天然温泉ゆったりCOco／都筑区中川中央2-7-1 港北みなも3F／大人 平日1,200円・土日祝1,500円／3歳未満・オムツの子は大浴場不可（貸切家族風呂は可）／18歳未満は23時まで', q:'港北天然温泉 ゆったりCOco' },
  { id:'yukemuri', at:{'あざみ野':'🚌 むりょうの バスで いくよ'}, icon:'🚌', name:'{湯|ゆ}けむりの{里|さと}', kind:'スーパーせんとう',
    open:[H(7), H(22)], rest:{}, restText:'おみせに きいてね',
    feat:['onsen','many','tanso','roten'], price:'こども 500えん（どにち 600えん）', baby:true,
    say:'あさ 7じから あいてる！ えきから ただの バスに のっていこう。',
    parent:'天然温泉 すすき野 湯けむりの里／青葉区すすき野3-2-7／あざみ野駅西口から無料シャトル（30分おき）／大人 平日850円・土日祝980円／0歳から入浴可との紹介あり（要確認）', q:'すすき野 湯けむりの里' },

  /* ───────── けいひんとうほくせん（さいたま） ───────── */
  { id:'wakamatsu-urawa', at:{'北浦和':'🚶 にしぐちから あるいて 5ふん'}, icon:'🪵', name:'{若松湯|わかまつゆ}', kind:'せんとう',
    open:[H(15), H(23)], rest:{dow:[3]}, restText:'すいようび',
    feat:['maki'], price:SEN.saitama, baby:true,
    say:'まきを もやして おゆを わかしている、むかしながらの おふろやさん。',
    parent:'さいたま市浦和区常盤10-10-15（北浦和ふれあい通り商店街）', q:'若松湯 浦和区常盤 銭湯' },
  { id:'koraku', at:{'北浦和':'🚶 あるいて 7ふん'}, icon:'🏯', name:'{湯屋敷|ゆやしき} {孝楽|こうらく}', kind:'スーパーせんとう',
    open:[H(10), H(25)], rest:{}, restText:'おみせに きいてね',
    feat:['roten','many','sauna'], price:'こども 350えん（どにち 400えん）／ 3さいまで ただ', baby:true,
    say:'そとの おふろや どうくつの おふろが あるよ。',
    parent:'湯屋敷 孝楽／さいたま市浦和区元町2-18-12／大人 平日750円・土日祝850円／7歳以上で身長120cm以上は異性の浴室不可／サウナ・岩盤浴は中学生から', q:'湯屋敷 孝楽 北浦和' },
  { id:'inari-urawa', at:{'浦和':'🚶 にしぐちから あるいて 8ぷん'}, icon:'⛩️', name:'{稲荷湯|いなりゆ}', kind:'せんとう',
    open:[H(16), H(20,45)], rest:{dow:[1], nth:[{dow:2, n:2}]}, restText:'げつようび（2しゅうめは かようびも）',
    feat:['car'], price:SEN.saitama, baby:true,
    say:'よる 9じまえに しまるから、ゆうがたに いこうね。',
    parent:'さいたま市浦和区仲町2-18-2', q:'稲荷湯 浦和 仲町 銭湯' },
  { id:'mitake', at:{'南浦和':'🚶 にしぐちから あるいて 11ぷん'}, icon:'⛰️', name:'みたけ{湯|ゆ}', kind:'せんとう',
    open:[H(15), H(22)], rest:{dow:[1]}, restText:'げつようび',
    feat:['retro'], price:SEN.saitama, baby:true,
    say:'むかしの ままの レトロな せんとう。シャンプーは もっていこうね。',
    parent:'さいたま市南区文蔵2-24-5／シャンプー類は持参', q:'みたけ湯 南区文蔵 銭湯' },
  { id:'kamenoyu-warabi', at:{'蕨':'🚶 にしぐちから あるいて 7ふん'}, icon:'🐢', name:'{亀|かめ}の{湯|ゆ}', kind:'せんとう',
    open:[H(14,30), H(21)], rest:{dow:[3]}, restText:'すいようび',
    feat:['sauna'], price:SEN.saitama, baby:true,
    say:'かめさんの なまえの おふろやさん。おとこゆと おんなゆが ひがわりだよ。',
    parent:'蕨市北町1-8-9／閉店は21時〜22時と情報により差があるため要確認', q:'亀の湯 蕨 北町 銭湯' },
  { id:'newmatsu-kawaguchi', at:{'蕨':'🚶 にしぐちから あるいて 12ふん'}, icon:'🌲', name:'ニュー{松|まつ}の{湯|ゆ}', kind:'せんとう',
    open:[H(15), H(23,30)], openDow:{0:[H(13), H(23,30)]}, rest:{dow:[2], nth:[{dow:3, n:1}]}, restText:'かようび・さいしょの すいようび',
    feat:['roten','sauna'], price:SEN.saitama, baby:true,
    say:'そとの おふろが ある せんとう。にちようびは ひるから あいてるよ。',
    parent:'川口市芝5-21-18', q:'ニュー松の湯 川口市芝 銭湯' },
  { id:'kirakuyu-kawaguchi', at:{'川口':'🚶 あるいて 15ふん', '西川口':'🚶 あるいて 15ふん'}, icon:'😄', name:'{喜楽湯|きらくゆ}', kind:'せんとう',
    open:[H(15), H(23)], rest:{dow:[5]}, restText:'きんようび',
    feat:['sauna'], price:SEN.saitama, baby:true,
    say:'どようびと にちようびは あさも やってるよ（8じ〜12じ）。',
    parent:'川口市川口5-21-6／土日は朝風呂8:00〜12:00もあり', q:'喜楽湯 川口 銭湯' },

  /* ───────── けいひんとうほくせん（とうきょう） ───────── */
  { id:'fujinoyu-akabane', at:{'赤羽':'🚶 あるいて 15ふん'}, icon:'🌸', name:'{藤|ふじ}の{湯|ゆ}', kind:'せんとう',
    open:[H(14,30), H(23,30)], rest:{dow:[4]}, restText:'もくようび',
    feat:['yaku','sauna'], price:SEN.tokyo, baby:true,
    say:'ひがわりの くすりの おふろが あるよ。',
    parent:'北区／埼京線・京浜東北線 赤羽駅から徒歩15分', q:'藤の湯 赤羽 銭湯' },
  { id:'yanagiyu', at:{'東十条':'🚶 あるいて 5ふん'}, icon:'🌿', name:'やなぎ{湯|ゆ}', kind:'せんとう',
    open:[H(14,30), H(23)], rest:{dow:[1]}, restText:'げつようび',
    feat:['roten','tanso','silk','denki','car'], price:SEN.tokyo, baby:true,
    say:'そとの しゅわしゅわ おふろが にんき！ ぬるい おふろも あるよ。',
    parent:'北区／露天炭酸泉・ぬる湯あり／無料駐車場あり', q:'やなぎ湯 東十条 銭湯' },
  { id:'ebisuyu-oji', at:{'王子':'🚶 あるいて 3ぷん'}, icon:'🗻', name:'えびす{湯|ゆ}', kind:'せんとう',
    open:[H(15), H(24)], rest:{dow:[1]}, restText:'げつようび',
    feat:['penki','bandai','maki','car'], price:SEN.tokyo, baby:true,
    say:'かべに おおきな ふじさんの え！ あすかやま こうえんの ちかくだよ。',
    parent:'北区／番台式／井戸水を薪で沸かす／ペンキ絵あり', q:'えびす湯 王子 銭湯' },
  { id:'cocofuro-kaga', at:{'王子':'🚶 あるいて 8ぷん'}, icon:'🌅', name:'COCOFURO かが{浴場|よくじょう}', kind:'せんとう',
    open:[H(6), H(24)], rest:{nth:[{dow:2, n:3, months:[3,5,9,11]}]}, restText:'3・5・9・11がつの 3しゅうめの かようび',
    feat:['asa','yaku','sauna'], price:SEN.tokyo, baby:true,
    say:'あさ 6じから あいてる あたらしい せんとう。',
    parent:'COCOFURO（ココフロ）かが浴場／北区／2023年オープン', q:'COCOFURO かが浴場 王子' },
  { id:'daikokuyu-kaminakazato', at:{'上中里':'🚶 あるいて 2ふん'}, icon:'🏠', name:'{大黒湯|だいこくゆ}', kind:'せんとう',
    open:[H(15), H(23)], rest:{dow:[2]}, restText:'かようび',
    feat:['roten','yaku','sauna','car'], price:SEN.tokyo, baby:true,
    say:'えきから すぐ！ アットホームな おふろやさん。',
    parent:'北区／日替わり薬湯／無料駐車場あり', q:'大黒湯 上中里 銭湯' },
  { id:'chitoseyu', at:{'西日暮里':'🚶 あるいて 5ふん', '田端':'🚶 あるいて 5ふん'}, icon:'🗻', name:'{千歳湯|ちとせゆ}', kind:'せんとう',
    open:[H(15,30), H(24)], rest:{dow:[5]}, restText:'きんようび',
    feat:['penki','yaku','retro'], price:SEN.tokyo, baby:true,
    say:'ふじさんの えと ひがわりの くすりの おふろ。レトロだよ。',
    parent:'荒川区／井戸水使用／手ぶらセットあり', q:'千歳湯 西日暮里 銭湯' },
  { id:'saitoyu', at:{'日暮里':'🚶 あるいて 3ぷん'}, icon:'🫧', name:'{日暮里|にっぽり} {斉藤湯|さいとうゆ}', kind:'せんとう',
    open:[H(14), H(23)], rest:{dow:[5]}, restText:'きんようび',
    feat:['roten','tanso','silk','denki'], price:SEN.tokyo, baby:true,
    say:'おふろも シャワーも やわらかい おみず。そとの いわぶろも あるよ。',
    parent:'荒川区／全て軟水／露天岩風呂（シルキー風呂）・炭酸泉', q:'日暮里 斉藤湯' },
  { id:'koganeyu-nippori', at:{'日暮里':'🚶 あるいて 7ふん'}, icon:'✨', name:'{黄金湯|こがねゆ}', kind:'せんとう',
    open:[H(15), H(23)], rest:{dow:[2]}, restText:'かようび',
    feat:['sauna'], price:SEN.tokyo, baby:true,
    say:'つよい ジェットの おふろが じまん。',
    parent:'荒川区', q:'黄金湯 日暮里 銭湯' },
  { id:'tsubameyu', at:{'御徒町':'🚶 あるいて 4ぷん'}, icon:'🐦', name:'{燕湯|つばめゆ}', kind:'せんとう',
    open:[H(6), H(20)], rest:{dow:[1,2]}, restText:'げつようび・かようび',
    feat:['asa','bandai','yaku'], price:SEN.tokyo, baby:true,
    say:'あさ 6じから やってる！ うえのの どうぶつえんの かえりにも いけるよ。',
    parent:'台東区／番台式／毎日朝湯／日曜は薬湯', q:'燕湯 御徒町 銭湯' },
  { id:'inariyu-kanda', at:{'神田':'🚶 あるいて 6ぷん'}, icon:'🎨', name:'{稲荷湯|いなりゆ}', kind:'せんとう',
    open:[H(14,40), H(22,30)], rest:{dow:[0]}, restText:'にちようび',
    feat:['penki'], price:SEN.tokyo, baby:true,
    say:'まいとし かきかえる かべの えが みどころ。',
    parent:'稲荷湯（神田）／千代田区／ペンキ絵は年1回描きかえ', q:'稲荷湯 神田 銭湯' },
  { id:'konparuyu', at:{'新橋':'🚶 あるいて 4ぷん', 'asakusa:新橋':'🚶 あるいて 5ふん くらい'}, icon:'⛩️', name:'{金春湯|こんぱるゆ}', kind:'せんとう',
    open:[H(14), H(22)], openDow:{6:[H(14), H(20)]}, rest:{dow:[0]}, restText:'にちようび・しゅくじつ',
    feat:['bandai','tile','penki'], price:SEN.tokyo, baby:true,
    say:'ぎんざの ちかくの むかしからの せんとう。おおきな かみだなが あるよ。',
    parent:'中央区（銀座八丁目）／番台式／九谷焼のタイル絵／祝日も休み', q:'金春湯 新橋 銭湯' },
  { id:'fureainoyu', at:{'浜松町':'🚶 あるいて 5ふん'}, icon:'🤝', name:'ふれあいの{湯|ゆ}', kind:'せんとう',
    open:[H(15), H(23)], openDow:{0:[H(14), H(23)]}, rest:{dow:[1]}, restText:'げつようび',
    feat:['rest'], price:SEN.tokyo, baby:true,
    say:'あがった あとに やすむ へやが あるよ。',
    parent:'港区／休憩室あり／ドライヤー無料', q:'ふれあいの湯 浜松町 銭湯' },
  { id:'suehiroyu', at:{'大井町':'🚶 あるいて 4ぷん'}, icon:'⬡', name:'すえひろ{湯|ゆ}', kind:'せんとう',
    open:[H(15), H(25)], openDow:{0:[H(10), H(25)], 6:[H(10), H(25)]}, rest:{}, restText:'おやすみ なし',
    feat:['ne','denki','sauna'], price:SEN.tokyo, baby:true,
    say:'はっかっけいの めずらしい あらいば！ どにちは あさ 10じから。',
    parent:'品川区／定休日なし／土日祝は10時から', q:'すえひろ湯 大井町 銭湯' },
  { id:'tokyoyokujo', at:{'大井町':'🚶 あるいて 7ふん'}, icon:'🎏', name:'{東京浴場|とうきょうよくじょう}', kind:'せんとう',
    open:[H(15), H(22)], rest:{dow:[1]}, restText:'げつようび',
    feat:['niwa','yaku'], price:SEN.tokyo, baby:true,
    say:'おにわに こいの いけが ある、おてらみたいな たてもの！',
    parent:'品川区／宮造り・中庭に鯉の池', q:'東京浴場 大井町 銭湯' },
  { id:'suijinyu', at:{'大森':'🚶 あるいて 6ぷん'}, icon:'💧', name:'{水神湯|すいじんゆ}', kind:'せんとう',
    open:[H(15), H(22)], rest:{dow:[1], until:'2026-10-15'}, restText:'げつようび（10がつ15にちまで こうじで おやすみ）',
    feat:['retro'], price:SEN.tokyo, baby:true,
    say:'からだの しんまで あったまる、やわらかい おゆ。',
    parent:'品川区／2026年10月5日〜15日は改修工事のため休業', q:'水神湯 大森 銭湯' },
  { id:'yucity-kamata', at:{'蒲田':'🚶 あるいて 5ふん'}, icon:'⚫', name:'ゆ〜シティー{蒲田|かまた}', kind:'せんとう',
    open:[H(11), H(24)], rest:{dow:[2]}, restText:'かようび',
    feat:['kuro','onsen','roten','sauna','car'], price:SEN.tokyo, baby:true,
    say:'まっくろな おんせんの そとの おふろ！ ひるから あいてるよ。',
    parent:'大田区／天然黒湯温泉／無料駐車場あり', q:'ゆ〜シティー蒲田' },
  { id:'kaiseiyu', at:{'蒲田':'🚶 あるいて 7ふん'}, icon:'⚫', name:'{改正湯|かいせいゆ}', kind:'せんとう',
    open:[H(15), H(23,30)], rest:{dow:[5]}, restText:'きんようび',
    feat:['kuro','onsen','tanso','silk','car'], price:SEN.tokyo, baby:true,
    say:'くろい おんせんの しゅわしゅわ おふろ。ちいさい こ づれでも あんしん。',
    parent:'大田区／黒湯天然温泉・黒湯炭酸泉／バリアフリー対応', q:'改正湯 蒲田 銭湯' },

  /* ───────── けいひんとうほくせん・ねぎしせん（かながわ） ───────── */
  { id:'masanoyu', at:{'川崎':'🚶 あるいて 5ふん', '京急川崎':'🚶 あるいて 7ふん くらい'}, icon:'♨️', name:'{政之湯|まさのゆ}', kind:'せんとう',
    open:[H(14), H(24)], rest:{date:[6,16,26]}, restText:'6・16・26にち',
    feat:['onsen','yaku','sauna'], price:SEN.kanagawa, baby:true,
    say:'かわさきえきの ちかくの おんせんの せんとう。',
    parent:'川崎市川崎区南町2-4（ビル1階）／天然温泉', q:'政之湯 川崎 銭湯' },
  { id:'kichinoyu', at:{'川崎':'🚶 ひがしぐちから あるいて 13ぷん'}, icon:'🧑‍🦳', name:'{吉|きち}の{湯|ゆ}', kind:'せんとう',
    open:[H(14,40), H(23)], rest:{dow:[6]}, restText:'どようび',
    feat:['bandai','retro'], price:SEN.kanagawa, baby:true,
    say:'ばんだいの ある むかしながらの おふろやさん。',
    parent:'川崎市川崎区貝塚2-5-8／番台式／休業日は公式Xで告知', q:'吉の湯 川崎区貝塚 銭湯' },
  { id:'ushiodayu', at:{'鶴見':'🚶 あるいて 10ぷん', '京急鶴見':'🚶 あるいて 8ぷん'}, icon:'🌱', name:'{潮田湯|うしおだゆ}', kind:'せんとう',
    open:[H(15), H(23)], rest:{dow:[5]}, restText:'きんようび',
    feat:['car'], price:SEN.kanagawa, baby:true,
    say:'おとこゆからは みどりの おんしつが みえるよ。',
    parent:'鶴見区本町通2-50（京急鶴見駅から徒歩8分）／駐車場5台', q:'潮田湯 鶴見 銭湯' },
  { id:'washinoyu', at:{'新子安':'🚶 あるいて 7ふん', '子安':'🚶 あるいて 4ぷん'}, icon:'🪨', name:'{鷲|わし}の{湯|ゆ}', kind:'せんとう',
    open:[H(11), H(24)], rest:{}, restText:'ときどき（おみせに きいてね）',
    feat:['onsen','car'], price:SEN.kanagawa, baby:true,
    say:'あきたけんの めずらしい いしの おふろが あるよ。',
    parent:'神奈川区七島町151（京急子安駅から徒歩4分）／北投石の湯／駐車場50台／不定休', q:'鷲の湯 子安 銭湯' },
  { id:'tokunoyu', at:{'東神奈川':'🚶 あるいて 10ぷん', '東白楽':'🚶 えきの すぐ まえ'}, icon:'🌳', name:'{徳|とく}の{湯|ゆ}', kind:'せんとう',
    open:[H(11), H(23)], openDow:{0:[H(9), H(23)]}, rest:{dow:[4]}, restText:'もくようび',
    feat:['roten'], price:SEN.kanagawa, baby:true,
    say:'そとの おふろが ある せんとう。ひるまから あいてるよ。',
    parent:'神奈川区西神奈川2-1-5（東急東横線 東白楽駅西口すぐ）／日祝は9時から', q:'徳の湯 東白楽 銭湯' },
  { id:'skyspa', at:{'横浜':'🚶 ひがしぐちから ちかで すぐ'}, icon:'🏙️', name:'スカイスパYOKOHAMA', kind:'スパ', adult:'ちゅうがくせいから',
    open:[H(0), H(24)], rest:{}, restText:'おやすみ なし（あさ そうじの じかん あり）',
    feat:['sauna'], price:'こどもは はいれません', baby:false,
    say:'おとなの ための おふろ。おおきく なったら いってみよう。',
    parent:'西区高島2-19-12 横浜スカイビル14F／中学生未満は利用不可／平日2,600円〜・休日3,300円〜', q:'スカイスパYOKOHAMA' },
  { id:'spaeas', at:{'横浜':'🚶 にしぐちから あるいて 5ふん'}, icon:'🪨', name:'SPA EAS', kind:'スパ', adult:'16さいから',
    open:[H(9,30), H(23)], rest:{}, restText:'おやすみ なし（てんけんの ひ あり）',
    feat:['onsen','roten','sauna'], price:'こどもは はいれません', baby:false,
    say:'おとなの ための おんせん。おおきく なったら いってみよう。',
    parent:'横浜天然温泉 SPA EAS／西区北幸2-2-1／16歳未満は利用不可／平日4,400円・土日祝5,200円／現金不可', q:'横浜天然温泉 SPA EAS' },
  { id:'manyo', at:{'桜木町':'🚶 あるいて 15ふん', '横浜':'🚌 にしぐちから むりょうの バス'}, icon:'🌉', name:'{万葉倶楽部|まんようくらぶ}', kind:'おんせん',
    open:[H(0), H(24)], rest:{}, restText:'おやすみ なし',
    feat:['onsen','ashiyu','many'], price:'しょうがくせい 1,500えん／ ようじ 1,800えん（たかめ）', baby:true,
    say:'おくじょうの あしゆから みなとみらいの よるの けしきが みえるよ。',
    parent:'横浜みなとみらい万葉倶楽部／中区新港2-7-1／横浜駅西口から無料シャトル／大人3,500円＋入湯税／24時間営業', q:'横浜みなとみらい 万葉倶楽部' },
  { id:'ebisuonsen', at:{'石川町':'🚶 あるいて 3ぷん'}, icon:'🏮', name:'{恵|え}びす{温泉|おんせん}', kind:'せんとう',
    open:[H(11), H(25)], rest:{dow:[2]}, restText:'かようび',
    feat:['many','sauna','yaku','car'], price:SEN.kanagawa, baby:true,
    say:'ちゅうかがいの すぐ ちかく！ いろんな おふろが あるよ。',
    parent:'中区山下町161／ラドン温泉・歩行浴・ミスト風呂', q:'恵びす温泉 石川町 銭湯' },
  { id:'koyamayu', at:{'石川町':'🚶 もとまちぐちから あるいて 3ぷん'}, icon:'⛰️', name:'{小山湯|こやまゆ}', kind:'せんとう',
    open:[H(9,30), H(21)], rest:{dow:[4,5]}, restText:'もくようび・きんようび',
    feat:['asa','yaku','car'], price:SEN.kanagawa, baby:true,
    say:'あさ 9じはんから あいてる！ もとまちの おかいものの あとに。',
    parent:'中区石川町3-106-4／駐車場5台', q:'小山湯 石川町 銭湯' },
  { id:'inariyu-yamate', at:{'山手':'🚶 あるいて 5ふん'}, icon:'🦊', name:'いなり{湯|ゆ}', kind:'せんとう',
    open:[H(15), H(23,30)], rest:{dow:[2]}, restText:'かようび',
    feat:['onsen','bandai','retro','denki'], price:SEN.kanagawa, baby:true,
    say:'ばんだいの ある しょうわの おふろやさん。おんせんだよ。',
    parent:'中区大和町1-12／番台式／天然温泉', q:'いなり湯 山手 銭湯' },
  { id:'dai2kouyou', at:{'根岸':'🚶 あるいて 12ふん'}, icon:'🌊', name:'{第二江陽館|だいにこうようかん}', kind:'せんとう',
    open:[H(14,10), H(23)], rest:{dow:[2]}, restText:'かようび',
    feat:['yaku','sauna','car'], price:SEN.kanagawa, baby:true,
    say:'ひがわりの くすりの おふろ。マンモスプールの ちかくだよ。',
    parent:'磯子区中浜町4-16／駐車場4台', q:'第二江陽館 磯子 銭湯' },
  { id:'taiseikan', at:{'根岸':'🚶 あるいて 16ぷん'}, icon:'🫧', name:'ねぎしの{湯|ゆ} {大盛舘|たいせいかん}', kind:'せんとう',
    open:[H(14), H(25)], rest:{dow:[2]}, restText:'かようび',
    feat:['roten','tanso','car'], price:SEN.kanagawa, baby:true,
    say:'そとの しゅわしゅわ おふろが にんき！',
    parent:'磯子区上町5-13／露天炭酸泉／駐車場あり／バスなら「根岸橋」下車徒歩2分', q:'ねぎしの湯 大盛舘' },
  { id:'ousama-konandai', at:{'港南台':'🚌 バスで 15ふん（「ひの」で おりる）'}, icon:'👑', name:'おふろの{王様|おうさま}', kind:'スーパーせんとう',
    open:[H(9), H(24)], rest:{}, restText:'おやすみ なし',
    feat:['onsen','roten','many'], price:'しょうがくせい 350えん／ ちいさい こ ただ', baby:true,
    say:'たけやぶの なかの そとの おふろが じまん！',
    parent:'おふろの王様 港南台店／港南区日野中央2-45-7／港南台駅から神奈中バス約15分「日野」下車', q:'おふろの王様 港南台店' },
  { id:'taya', at:{'本郷台':'🚌 むりょうの バスで いくよ'}, icon:'🍃', name:'{湯快爽快|ゆかいそうかい} たや', kind:'スーパーせんとう',
    open:[H(10), H(24)], rest:{}, restText:'てんけんの ひ（おみせに きいてね）',
    feat:['onsen','roten','many'], price:'こども 350えん（3さい〜しょうがくせい）／ 2さいまで ただ', baby:true,
    say:'えきから ただの バスで いける おんせん。かようびは こどもが やすいよ。',
    parent:'野天湯元 湯快爽快 たや／栄区田谷町146-3／本郷台駅から無料シャトル／火曜はキッズデー（小学生以下300円）／2026年10月15日から小学生以下だけの入館不可／オムツの子は浴槽不可', q:'野天湯元 湯快爽快 たや' },
  { id:'hibariyu', at:{'大船':'🚶 ひがしぐちから あるいて 3ぷん'}, icon:'🐤', name:'ひばり{湯|ゆ}', kind:'せんとう',
    open:[H(13), H(23)], openDow:{0:[H(10,30), H(23)], 6:[H(10,30), H(23)]}, rest:{dow:[3], nth:[{dow:4, n:3}]}, restText:'すいようび・3しゅうめの もくようび',
    feat:['tanso','ne','denki','sauna'], price:SEN.kanagawa, baby:true,
    say:'しゅわしゅわの おふろが にんき。かまくらの おでかけの あとに。',
    parent:'鎌倉市大船1-13-7（大船仲通り商店街付近）／土日は10:30から', q:'ひばり湯 大船 銭湯' },

  /* ───────── とうよこせん ───────── */
  { id:'sakaeyu-shibuya', at:{'渋谷':'🚶 あるいて 8ぷん'}, icon:'🪵', name:'さかえ{湯|ゆ}', kind:'せんとう',
    open:[H(15,30), H(25)], rest:{dow:[5]}, restText:'きんようび',
    feat:['bandai','maki'], price:SEN.tokyo, baby:true,
    say:'しぶやの ちかくで まきを もやして わかす あつめの おゆ。',
    parent:'渋谷区／番台式／シャンプー・ボディソープあり（手ぶらOK）／金曜休み（銭湯の日・しょうぶ湯・ゆず湯は営業）', q:'さかえ湯 渋谷 銭湯' },
  { id:'kairyoyu', at:{'渋谷':'🚶 あるいて 12ふん'}, icon:'🎨', name:'{改良湯|かいりょうゆ}', kind:'せんとう',
    open:[H(12), H(23,30)], rest:{dow:[6]}, restText:'どようび',
    feat:['tanso','penki','sauna'], price:SEN.tokyo, baby:true,
    say:'おおきな しゅわしゅわ おふろと、かべの げんだいアートの え。',
    parent:'渋谷区（恵比寿駅からも徒歩12分）／炭酸泉・軟水・ぬる湯', q:'改良湯 渋谷 銭湯' },
  { id:'komeisen', at:{'中目黒':'🚶 あるいて 3ぷん'}, icon:'🏙️', name:'{光明泉|こうめいせん}', kind:'せんとう',
    open:[H(15), H(25)], rest:{}, restText:'ときどき（おみせに きいてね）',
    feat:['roten','tanso','sauna','penki'], price:SEN.tokyo, baby:true,
    say:'おくじょうに そとの おふろが ある！ しゅわしゅわ おふろも あるよ。',
    parent:'目黒区／屋上露天風呂は男女週替わり／不定休', q:'光明泉 中目黒 銭湯' },
  { id:'chiyonoyu', at:{'学芸大学':'🚶 あるいて 2ふん'}, icon:'💎', name:'{千代|ちよ}の{湯|ゆ}', kind:'せんとう',
    open:[H(15,30), H(24)], rest:{dow:[1]}, restText:'げつようび',
    feat:['tanso','penki','retro'], price:SEN.tokyo, baby:true,
    say:'「みずの ほうせき」って よばれる やわらかい おゆ。ふじさんの えも あるよ。',
    parent:'目黒区／軟水風呂・炭酸泉／ペンキ絵', q:'千代の湯 学芸大学 銭湯' },
  { id:'asahiyu-toritsu', at:{'都立大学':'🚶 あるいて 1ぷん'}, icon:'🌅', name:'{旭湯|あさひゆ}', kind:'せんとう',
    open:[H(15,30), H(23)], rest:{dow:[1]}, restText:'げつようび',
    feat:['sauna'], price:SEN.tokyo, baby:true,
    say:'えきから 1ぷん！ てんじょうが たかくて ひろい おふろ。',
    parent:'目黒区／ミストサウナ無料', q:'旭湯 都立大学 銭湯' },
  { id:'midoriyu-jiyugaoka', at:{'自由が丘':'🚶 あるいて 7ふん'}, icon:'🗻', name:'みどり{湯|ゆ}', kind:'せんとう',
    open:[H(13), H(22)], rest:{dow:[4]}, restText:'もくようび',
    feat:['penki','sauna'], price:SEN.tokyo, baby:true,
    say:'しろと くろの かっこいい ふじさんの え が おでむかえ。',
    parent:'目黒区', q:'みどり湯 自由が丘 銭湯' },
  { id:'imaiyu', at:{'武蔵小杉':'🚶 あるいて 10ぷん', '元住吉':'🚶 あるいて 10ぷん'}, icon:'🥛', name:'{今井湯|いまいゆ}', kind:'せんとう',
    open:[H(15), H(24)], openDow:{0:[H(7), H(24)], 6:[H(7), H(24)]}, rest:{nth:[{dow:3, n:1}, {dow:3, n:3}, {dow:3, n:5}]}, restText:'1・3・5しゅうめの すいようび',
    feat:['tanso','silk','sauna','asa'], price:SEN.kanagawa, baby:true,
    say:'あさ 7じからも やってるよ。シルクの おふろは ぬるめで きもちいい。',
    parent:'川崎市中原区今井南町34-25／平日は朝7〜10時と15〜24時、土日祝は7〜24時／オール軟水', q:'今井湯 川崎 中原区 銭湯' },
  { id:'asahiyu-hiyoshi', at:{'日吉':'🚶 あるいて 7ふん'}, icon:'🌿', name:'{旭湯|あさひゆ}', kind:'せんとう',
    open:[H(14,30), H(23)], rest:{dow:[4]}, restText:'もくようび',
    feat:['roten','yaku','sauna','car'], price:SEN.kanagawa, baby:true,
    say:'そとの おふろが ひがわりの くすりの おふろに なるよ。',
    parent:'港北区日吉2-15-31／駐車場4台', q:'旭湯 日吉 銭湯' },
  { id:'yukemurinosho', at:{'綱島':'🚌 むりょうの バスで 6ぷん'}, icon:'🏞️', name:'{湯|ゆ}けむりの{庄|しょう}', kind:'スーパーせんとう',
    open:[H(9), H(24)], rest:{}, restText:'おみせに きいてね',
    feat:['onsen','roten','many'], price:'しょうがくせい 1,180えん（どにち 1,320えん）', baby:false,
    say:'しょうがくせいに なったら はいれる おおきな おんせん。',
    parent:'綱島源泉 湯けむりの庄／港北区樽町3-7-61／綱島駅から無料シャトル約6分（徒歩18分）／小学生以上のみ入館可／大人 平日1,540円・土日祝1,700円', q:'綱島源泉 湯けむりの庄' },
  { id:'taiheikan', at:{'大倉山':'🚶 ひがしぐちから あるいて 9ふん'}, icon:'⚫', name:'{太平館|たいへいかん}', kind:'せんとう',
    open:[H(15,30), H(22)], rest:{dow:[1,5]}, restText:'げつようび・きんようび',
    feat:['kuro','onsen','bandai','retro'], price:SEN.kanagawa, baby:true,
    say:'くろい おゆの おんせん！ ばんだいの ある レトロな おふろやさん。',
    parent:'港北区大曽根1-25-2／天然ラジウム温泉（黒湯）／番台式', q:'太平館 大倉山 銭湯' },

  /* ───────── そうてつせん ───────── */
  { id:'banzaiyu', at:{'平沼橋':'🚶 あるいて 7ふん', '戸部':'🚶 あるいて 5ふん'}, icon:'🌲', name:'{萬歳湯|ばんざいゆ}', kind:'せんとう',
    open:[H(14), H(21)], rest:{dow:[6]}, restText:'どようび',
    feat:['bandai','hinoki'], price:SEN.kanagawa, baby:true,
    say:'ひのきの おふろが ある ばんだいの せんとう。とべこうえんの すぐ そば。',
    parent:'西区中央1-23-3（京急戸部駅から徒歩5分）／番台式／受付は20:30まで', q:'萬歳湯 戸部 銭湯' },
  { id:'asahiyu-nishiyokohama', at:{'西横浜':'🚶 あるいて 10ぷん', '戸部':'🚶 あるいて 10ぷん'}, icon:'🔥', name:'{朝日湯|あさひゆ}', kind:'せんとう',
    open:[H(14,30), H(23)], rest:{}, restText:'ときどき（おみせに きいてね）',
    feat:['retro'], price:SEN.kanagawa, baby:true,
    say:'あつめの おゆ。ちいさい こは うめて もらおうね。',
    parent:'西区中央2-44-6（京急戸部駅からも徒歩10分）／湯船は熱め／不定休', q:'朝日湯 横浜 西区中央 銭湯' },
  { id:'nakanoyu-fujidana', at:{'西横浜':'🚶 あるいて 11ぷん'}, icon:'🐟', name:'{中乃湯|なかのゆ}', kind:'せんとう',
    open:[H(15), H(22)], rest:{dow:[4]}, restText:'もくようび',
    feat:['koi','bandai','yaku'], price:SEN.kanagawa, baby:true,
    say:'あらいばに こいが およいでる すいそうが あるよ！',
    parent:'西区藤棚町2-197-37（藤棚県営団地内）／番台式／洗い場に鯉の水槽', q:'中乃湯 藤棚 銭湯' },
  { id:'kikunoyu-hoshikawa', at:{'星川':'🚶 あるいて 6ぷん'}, icon:'🌼', name:'{喜久|きく}の{湯|ゆ}', kind:'せんとう',
    open:[H(15), H(23)], rest:{dow:[3]}, restText:'すいようび',
    feat:['ne','denki','yaku','sauna','car'], price:SEN.kanagawa, baby:true,
    say:'きせつの くすりの おふろや ねころぶ おふろが あるよ。',
    parent:'保土ケ谷区川辺町15-5 星川シュロス（国道16号沿い）／駐車場5台', q:'喜久の湯 星川 銭湯' },
  { id:'koganeyu-wadamachi', at:{'和田町':'🚶 あるいて 10ぷん', '上星川':'🚶 あるいて 12ふん'}, icon:'🌊', name:'{黄金湯|こがねゆ}', kind:'せんとう',
    open:[H(15), H(22,30)], rest:{dow:[5]}, restText:'きんようび',
    feat:['onsen','sauna'], price:SEN.kanagawa, baby:true,
    say:'むかしの うみの みずから できた めずらしい おんせん。',
    parent:'横浜温泉 黄金湯／保土ケ谷区仏向町245-1／天然化石海水型温泉', q:'横浜温泉 黄金湯 仏向町' },
  { id:'kamihoshikawa-yokujo', at:{'上星川':'🚶 みなみぐちから あるいて 1ぷん'}, icon:'🏪', name:'{上星川浴場|かみほしかわよくじょう}', kind:'せんとう',
    open:[H(14,30), H(22)], rest:{dow:[1,2]}, restText:'げつようび・かようび',
    feat:['sauna','denki','yaku'], price:SEN.kanagawa, baby:true,
    say:'えきを でて すぐ！ しょうてんがいの いりぐちに あるよ。',
    parent:'保土ケ谷区上星川3-3-1（上星川商店会入口）', q:'上星川浴場 銭湯' },
  { id:'mantennoyu', at:{'上星川':'🚶 えきの まえ'}, icon:'🌟', name:'{満天|まんてん}の{湯|ゆ}', kind:'スーパーせんとう',
    open:[H(6), H(25)], rest:{nth:[{dow:2, n:3}]}, restText:'3しゅうめの かようび',
    feat:['onsen','roten','many','car'], price:'しょうがくせい 400えん／ ちいさい こ 250えん', baby:true,
    say:'あさ 6じから あいてる おんせん。えきの すぐ まえだよ。',
    parent:'天然温泉 満天の湯／保土ケ谷区上星川／大人 平日1,100円・土日祝1,200円（2026年3月改定）／10/20・21は休館', q:'天然温泉 満天の湯 上星川' },
  { id:'sakurayu-mitsukyo', at:{'三ツ境':'🚶 みなみぐちから あるいて 3ぷん'}, icon:'🌸', name:'{桜湯|さくらゆ}', kind:'せんとう',
    open:[H(14), H(23,30)], rest:{dow:[2,5]}, restText:'かようび・きんようび',
    feat:['many','roten','sauna','car'], price:SEN.kanagawa, baby:true,
    say:'12しゅるいの おふろと そとの おふろ！ おとこゆと おんなゆは ひがわり。',
    parent:'瀬谷区三ツ境12-10／駐車場25台／手ぶらセットあり', q:'桜湯 三ツ境 銭湯' },
  { id:'ousama-ebina', at:{'かしわ台':'🚶 にしぐちから あるいて 4ぷん'}, icon:'👑', name:'おふろの{王様|おうさま} {海老名|えびな}', kind:'スーパーせんとう',
    open:[H(9), H(24)], rest:{}, restText:'おやすみ なし（てんけんの ひ あり）',
    feat:['onsen','roten','many'], price:'しょうがくせい 350えん／ ちいさい こ ただ', baby:true,
    say:'ちいさい こは ただで はいれる おふろの おうさま！',
    parent:'おふろの王様 海老名店／海老名市柏ヶ谷3-6-8／大人 平日900円・土日祝1,050円（一般）', q:'おふろの王様 海老名店' },
  { id:'raku-shonandai', at:{'湘南台':'🚶 あるいて 2ふん'}, icon:'♨️', name:'{湘南台温泉|しょうなんだいおんせん} らく', kind:'スーパーせんとう',
    open:[H(10), H(24)], rest:{nth:[{dow:1, n:3}]}, restText:'3しゅうめの げつようび',
    feat:['onsen','many'], price:'こども 300えん（3〜11さい・オムツが とれた こ）', baby:false,
    say:'ゆがわら おんせんの おゆを はこんで きている おふろ。',
    parent:'湘南台温泉 らく／藤沢市湘南台2-7-5／大人 平日880円・土日祝980円／3歳未満は入浴不可／深夜営業あり（曜日で異なる）', q:'湘南台温泉 らく' },

  /* ───────── けいきゅうせん ───────── */
  { id:'fukiageyu', at:{'北品川':'🚶 あるいて 2ふん'}, icon:'🔥', name:'{吹上湯|ふきあげゆ}', kind:'せんとう',
    open:[H(15,30), H(22,30)], rest:{dow:[3,6]}, restText:'すいようび・どようび',
    feat:['retro'], price:SEN.tokyo, baby:true,
    say:'すみの はいった なめらかな おゆ。すこし あついよ。',
    parent:'品川区北品川1-25-12／明治創業／備長炭入りのお湯（熱め）', q:'吹上湯 北品川 銭湯' },
  { id:'tenjinyu-kitashinagawa', at:{'新馬場':'🚶 あるいて 3ぷん'}, icon:'♨️', name:'{北品川温泉|きたしながわおんせん} {天神湯|てんじんゆ}', kind:'せんとう',
    open:[H(15), H(23)], rest:{dow:[5]}, restText:'きんようび',
    feat:['onsen'], price:SEN.tokyo, baby:true,
    say:'おんせんの せんとう。ひろい ロビーで ゆっくり できるよ。',
    parent:'品川区北品川2-23-9／天然温泉／バリアフリー', q:'北品川温泉 天神湯' },
  { id:'tenguyu', at:{'平和島':'🚶 あるいて 6ぷん'}, icon:'👺', name:'{天狗湯|てんぐゆ}', kind:'せんとう',
    open:[H(14,30), H(22,30)], rest:{dow:[4], nth:[{dow:3, n:3}]}, restText:'もくようび・3しゅうめの すいようび',
    feat:['onsen','denki','sauna'], price:SEN.tokyo, baby:true,
    say:'てんぐの なまえの おんせんの せんとう！',
    parent:'大田区／天然温泉', q:'天狗湯 平和島 銭湯' },
  { id:'omoriyu', at:{'大森町':'🚶 あるいて 3ぷん'}, icon:'🌿', name:'{大森湯|おおもりゆ}', kind:'せんとう',
    open:[H(15), H(23)], rest:{nth:[{dow:2, n:2}, {dow:2, n:4}, {dow:2, n:5}]}, restText:'2・4・5しゅうめの かようび',
    feat:['yaku','sauna','retro'], price:SEN.tokyo, baby:true,
    say:'ようびで かわる くすりの おふろ。きょうは なにの おふろかな？',
    parent:'大田区大森西3-8-17／日替わり薬湯・天然トルマリン風呂', q:'大森湯 大森町 銭湯' },
  { id:'atariyu', at:{'大森町':'🚶 あるいて 10ぷん'}, icon:'🎏', name:'あたり{湯|ゆ}', kind:'せんとう',
    open:[H(15,30), H(23,30)], rest:{dow:[1]}, restText:'げつようび',
    feat:['niwa','maki','sauna'], price:SEN.tokyo, baby:true,
    say:'まきで わかす おゆと、きれいな おにわが じまん。',
    parent:'大田区大森西3-11-27／乾式サウナ無料', q:'あたり湯 大森町 銭湯' },
  { id:'tenjinyu-kamata', at:{'京急蒲田':'🚶 あるいて 4ぷん'}, icon:'🏢', name:'{天神湯|てんじんゆ}', kind:'せんとう',
    open:[H(14), H(24)], rest:{dow:[4]}, restText:'もくようび',
    feat:['nikai','roten','sauna','car'], price:SEN.tokyo, baby:true,
    say:'1かいと 2かいで ちがう おふろ。まいにち おとこゆと おんなゆが いれかわるよ。',
    parent:'大田区／無料駐車場あり', q:'天神湯 京急蒲田 銭湯' },
  { id:'kotobukiyu-kamata', at:{'京急蒲田':'🚶 にしぐちから あるいて 5ふん'}, icon:'⭕', name:'{寿湯|ことぶきゆ}', kind:'せんとう',
    open:[H(15,30), H(23,45)], rest:{dow:[1]}, restText:'げつようび',
    feat:['maru','maki','sauna','car'], price:SEN.tokyo, baby:true,
    say:'おふろばの まんなかに まあるい おおきな おふろが あるよ！',
    parent:'大田区／浴室中央に直径4mの丸い浴槽／薪沸かし／無料駐車場', q:'寿湯 京急蒲田 銭湯' },
  { id:'nuland-sagamiyu', at:{'雑色':'🚶 あるいて 3ぷん'}, icon:'⚫', name:'ヌーランド さがみ{湯|ゆ}', kind:'せんとう',
    open:[H(10), H(23)], rest:{}, restText:'おやすみ なし',
    feat:['kuro','onsen','roten','many','car'], price:SEN.tokyo, baby:true,
    say:'くろい おんせんと 8しゅるいの おふろ。あさ 10じから やってるよ。',
    parent:'大田区仲六郷／天然黒湯温泉・食事処あり／無休', q:'ヌーランド さがみゆ 雑色' },
  { id:'terunoyu', at:{'雑色':'🚶 あるいて 5ふん'}, icon:'⚫', name:'{照|てる}の{湯|ゆ}', kind:'せんとう',
    open:[H(15), H(22)], rest:{dow:[3,4]}, restText:'すいようび・もくようび',
    feat:['kuro','onsen','roten','hinoki','penki'], price:SEN.tokyo, baby:true,
    say:'そとの おふろも みずぶろも くろい おんせん！',
    parent:'大田区／黒湯の露天風呂・古代ひのき風呂', q:'照の湯 雑色 銭湯' },
  { id:'sachinoyu', at:{'糀谷':'🚶 あるいて 5ふん'}, icon:'🌅', name:'{幸|さち}の{湯|ゆ}', kind:'せんとう',
    open:[H(6), H(23)], rest:{dow:[1]}, restText:'げつようび',
    feat:['asa','onsen','roten','sauna'], price:SEN.tokyo, baby:true,
    say:'まいあさ 6じから あいてる おんせんの せんとう。',
    parent:'大田区／朝6〜11時と14〜23時（11〜14時は休憩）／天然温泉', q:'幸の湯 糀谷 銭湯' },
  { id:'kannonyu', at:{'糀谷':'🚶 あるいて 7ふん'}, icon:'🚀', name:'{観音湯|かんのんゆ}', kind:'せんとう',
    open:[H(16), H(23,30)], rest:{}, restText:'ときどき（おみせに きいてね）',
    feat:['uchu','bandai','sauna'], price:SEN.tokyo, baby:true,
    say:'かべに うちゅうの え！ ほしを みながら おふろに はいろう。',
    parent:'大田区／番台式／宇宙がテーマの背景画／不定休', q:'観音湯 糀谷 銭湯' },
  { id:'takarayu-otorii', at:{'大鳥居':'🚶 あるいて 2ふん'}, icon:'💰', name:'{宝湯|たからゆ}', kind:'せんとう',
    open:[H(15,30), H(23,30)], rest:{dow:[1,4]}, restText:'げつようび・もくようび',
    feat:['yaku','sauna','car'], price:SEN.tokyo, baby:true,
    say:'どにちは くすりの おふろが にんき。えきから すぐ！',
    parent:'大田区／無料駐車場あり', q:'宝湯 大鳥居 銭湯' },
  { id:'takenoyu-otorii', at:{'大鳥居':'🚶 あるいて 4ぷん'}, icon:'🎋', name:'{竹|たけ}の{湯|ゆ}', kind:'せんとう',
    open:[H(16), H(23,30)], rest:{dow:[3]}, restText:'すいようび',
    feat:['bandai','maki','ne','yaku','sauna'], price:SEN.tokyo, baby:true,
    say:'まきで わかした やわらかい おゆ。ねころぶ おふろも あるよ。',
    parent:'大田区／番台式', q:'竹の湯 大鳥居 銭湯' },
  { id:'shigenoyu', at:{'穴守稲荷':'🚶 あるいて 10ぷん'}, icon:'🗻', name:'{重|しげ}の{湯|ゆ}', kind:'せんとう',
    open:[H(15), H(24)], rest:{dow:[2,6]}, restText:'かようび・どようび',
    feat:['bandai','niwa','penki','yaku'], price:SEN.tokyo, baby:true,
    say:'おてらみたいな たてものと ふじさんの え。おにわも きれい。',
    parent:'大田区羽田／宮造り・庭・富士山のペンキ絵', q:'重の湯 穴守稲荷 銭湯' },
  { id:'asahiyu-namamugi', at:{'生麦':'🚶 あるいて 3ぷん'}, icon:'⛩️', name:'{朝日湯|あさひゆ}', kind:'せんとう',
    open:[H(15), H(22)], rest:{date:[5,15,25]}, restText:'5・15・25にち（ほかにも おやすみ あり）',
    feat:['onsen','bandai','sauna','car'], price:SEN.kanagawa, baby:true,
    say:'おてらみたいな たてものの おんせんの せんとう。',
    parent:'鶴見区生麦3-6-24／番台式／天然温泉／日曜の場合は翌日休み・不定休あり', q:'朝日湯 生麦 銭湯' },
  { id:'takenoyu-namamugi', at:{'生麦':'🚶 あるいて 5ふん'}, icon:'🍺', name:'{竹|たけ}の{湯|ゆ}', kind:'せんとう',
    open:[H(15), H(22)], rest:{}, restText:'ときどき（おみせに きいてね）',
    feat:['roten','tanso','yaku','sauna'], price:SEN.kanagawa, baby:true,
    say:'キリンビールの こうじょうの ちかく。そとの おふろも あるよ。',
    parent:'鶴見区生麦3-14-2／日替わり入浴／不定休', q:'竹の湯 生麦 銭湯' },
  { id:'kusatsu', at:{'井土ヶ谷':'🚶 あるいて 5ふん'}, icon:'♨️', name:'{横浜天然温泉|よこはまてんねんおんせん}くさつ', kind:'せんとう',
    open:[H(12), H(23)], openDow:{0:[H(10), H(23)], 6:[H(10), H(23)]}, rest:{dow:[1]}, restText:'げつようび（しゅくじつは やってる）',
    feat:['onsen','roten','hinoki','sauna','car'], price:SEN.kanagawa, baby:true,
    say:'ぜんぶの おふろが おんせん！ どにちは あさ 10じから。',
    parent:'南区井土ヶ谷上町21-29／土日祝は10時から／駐車場12台／軽食コーナーあり', q:'横浜天然温泉くさつ' },
  { id:'suehiroyu-daishi', at:{'川崎大師':'🚶 あるいて 1ぷん'}, icon:'🙏', name:'{寿恵弘湯|すえひろゆ}', kind:'せんとう',
    open:[H(15), H(24)], rest:{}, restText:'ときどき（おみせに きいてね）',
    feat:['silk','ne','yaku','sauna'], price:SEN.kanagawa, baby:true,
    say:'かわさきだいしの ちかく。おふろの あとは ソフトクリームも あるよ。',
    parent:'川崎市川崎区大師駅前1-6-20（ごりやく通り）／休業日は公式Xで告知', q:'寿恵弘湯 川崎大師' },
  { id:'newmatsu-oppama', at:{'追浜':'🚶 あるいて 10ぷん'}, icon:'🌲', name:'アクアスポット ニュー{松|まつ}の{湯|ゆ}', kind:'せんとう',
    open:[H(14), H(22)], rest:{}, restText:'ときどき（おみせに きいてね）',
    feat:['retro'], price:SEN.kanagawa, baby:true,
    say:'おっぱまの まちの おふろやさん。',
    parent:'横須賀市追浜東町3-47／当面不定休（店舗HPで確認）', q:'アクアスポット ニュー松の湯 追浜' },
  { id:'minatoyu-mutsuura', at:{'追浜':'🚶 あるいて 10ぷん'}, icon:'🌲', name:'みなと{湯|ゆ}', kind:'せんとう',
    open:[H(15), H(22)], rest:{dow:[4]}, restText:'もくようび',
    feat:['hinoki','retro','car'], price:SEN.kanagawa, baby:true,
    say:'ぜんぶ ひのきで できた レトロな おふろやさん。',
    parent:'金沢区六浦東3-1-23／木造総桧造り／駐車場あり', q:'みなと湯 金沢区 六浦 銭湯' },
  { id:'kamenoyu-shioiri', at:{'汐入':'🚶 あるいて 5〜8ふん'}, icon:'🐢', name:'{亀|かめ}の{湯|ゆ}', kind:'せんとう',
    open:[H(16), H(20)], rest:{dow:[1,4]}, restText:'げつようび・もくようび',
    feat:['maki','penki','retro'], price:SEN.kanagawa, baby:true,
    say:'まきで わかす むかしの ままの せんとう。よる 8じで しまるよ。',
    parent:'横須賀市汐入町5-2／営業時間は情報により差があるため要確認', q:'亀の湯 汐入 銭湯' },
  { id:'matsunoyu-yokosuka', at:{'県立大学':'🚶 あるいて 4ぷん'}, icon:'🌲', name:'{松|まつ}の{湯|ゆ}', kind:'せんとう',
    open:[H(14,30), H(22)], rest:{dow:[5]}, restText:'きんようび',
    feat:['retro'], price:SEN.kanagawa, baby:true,
    say:'けんりつだいがくえきの ちかくの まちの せんとう。',
    parent:'横須賀市安浦町2-22', q:'松の湯 横須賀 安浦町 銭湯' },
  { id:'miyamotoonsen', at:{'京急大津':'🚶 あるいて 3ぷん', '新大津':'🚶 あるいて 10ぷん'}, icon:'🚗', name:'{宮本温泉|みやもとおんせん}', kind:'せんとう',
    open:[H(15), H(23)], rest:{dow:[5]}, restText:'きんようび',
    feat:['car'], price:SEN.kanagawa, baby:true,
    say:'えきから 3ぷん。ちゅうしゃじょうも あるよ。',
    parent:'横須賀市大津町3-7-3／駐車場6台', q:'宮本温泉 京急大津 銭湯' },
  { id:'manyoyu-kurihama', at:{'京急久里浜':'🚶 にしぐちから あるいて 3〜5ふん'}, icon:'🛋️', name:'{万葉湯|まんようゆ}', kind:'せんとう',
    open:[H(13), H(23)], rest:{dow:[2]}, restText:'かようび',
    feat:['rest','car'], price:SEN.kanagawa, baby:true,
    say:'おふろの あと 2かいの ひろい おへやで ゆっくり できるよ。',
    parent:'やすらぎの湯 万葉／横須賀市久里浜1-6-1／2階に大広間／駐車場8台', q:'万葉湯 京急久里浜 銭湯' },

  /* ───────── とえい あさくさせん ───────── */
  { id:'kugaharayu', at:{'西馬込':'🚶 あるいて 14ぷん'}, icon:'⚫', name:'{久|く}が{原湯|はらゆ}', kind:'せんとう',
    open:[H(14), H(24)], rest:{dow:[1], nth:[{dow:2, n:4}]}, restText:'げつようび・4しゅうめの かようび',
    feat:['kuro','onsen','roten','tanso'], price:SEN.tokyo, baby:true,
    say:'60ねん つづく くろい おんせん。しゅわしゅわ おふろも あるよ。',
    parent:'大田区／黒湯天然温泉／ぬる湯あり', q:'久が原湯 銭湯' },
  { id:'matsunoyu-nakanobu', at:{'中延':'🚶 あるいて 3ぷん'}, icon:'🏯', name:'{中延温泉|なかのぶおんせん} {松|まつ}の{湯|ゆ}', kind:'せんとう',
    open:[H(15), H(24)], rest:{dow:[1]}, restText:'げつようび',
    feat:['onsen','roten','tanso','yaku'], price:SEN.tokyo, baby:true,
    say:'てんじょうが たかい おてらみたいな おんせん。',
    parent:'品川区／宮造り／東急中延駅から徒歩2分', q:'中延温泉 松の湯' },
  { id:'togoshiginza-onsen', at:{'戸越':'🚶 あるいて 3ぷん'}, icon:'⚫', name:'{戸越銀座温泉|とごしぎんざおんせん}', kind:'せんとう',
    open:[H(15), H(25)], rest:{dow:[5]}, restText:'きんようび',
    feat:['kuro','onsen','roten','penki','car'], price:SEN.tokyo, baby:true,
    say:'とごしぎんざ しょうてんがいの くろい おんせん！',
    parent:'品川区／黒湯天然温泉／2種類の浴室を週替わり', q:'戸越銀座温泉' },
  { id:'ginzayu', at:{'宝町':'🚶 あるいて 2ふん'}, icon:'🏙️', name:'{銀座湯|ぎんざゆ}', kind:'せんとう',
    open:[H(15), H(23)], rest:{dow:[0]}, restText:'にちようび・しゅくじつ',
    feat:['bandai'], price:SEN.tokyo, baby:true,
    say:'ぎんざの まんなかに ある ばんだいの せんとう。',
    parent:'中央区銀座1丁目／番台式／祝日も休み', q:'銀座湯 宝町 銭湯' },
  { id:'bentenyu-asakusabashi', at:{'浅草橋':'🚶 あるいて 2ふん'}, icon:'⛩️', name:'{辨天湯|べんてんゆ}', kind:'せんとう',
    open:[H(15,30), H(23)], rest:{nth:[{dow:1, n:2}, {dow:1, n:4}]}, restText:'2・4しゅうめの げつようび',
    feat:['retro'], price:SEN.tokyo, baby:true,
    say:'マンションの いりぐちの べんてんさまが めじるし。',
    parent:'台東区／荷物一時預かりあり', q:'辨天湯 浅草橋 銭湯' },
  { id:'teikokuyu', at:{'浅草橋':'🚶 あるいて 6ぷん'}, icon:'👑', name:'{帝国湯|ていこくゆ}', kind:'せんとう',
    open:[H(15), H(23,30)], rest:{dow:[1]}, restText:'げつようび',
    feat:['bandai','yaku'], price:SEN.tokyo, baby:true,
    say:'あつめの おゆが すきな ひとに。ばんだいの せんとう。',
    parent:'台東区／番台式／熱め', q:'帝国湯 浅草橋 銭湯' },
  { id:'misujiyu', at:{'蔵前':'🚶 あるいて 8ぷん'}, icon:'🗻', name:'{三筋湯|みすじゆ}', kind:'せんとう',
    open:[H(15), H(22)], rest:{dow:[1,2]}, restText:'げつようび・かようび',
    feat:['bandai','maki','penki','niwa'], price:SEN.tokyo, baby:true,
    say:'おてらみたいな たてもの。まきで わかす おゆと ふじさんの え。',
    parent:'台東区／宮造り・番台式・薪沸かし', q:'三筋湯 蔵前 銭湯' },
  { id:'araiyu', at:{'本所吾妻橋':'🚶 あるいて 10ぷん'}, icon:'🎏', name:'{荒井湯|あらいゆ}', kind:'せんとう',
    open:[H(15,30), H(23,30)], rest:{dow:[3]}, restText:'すいようび',
    feat:['bandai','yaku','niwa','penki','car'], price:SEN.tokyo, baby:true,
    say:'おにわの ある したまちの せんとう。ぬるい おふろも あるよ。',
    parent:'墨田区／番台式／日替わり薬湯・あつ湯とぬる湯', q:'荒井湯 本所吾妻橋 銭湯' },
  { id:'sakurayu-oshiage', at:{'押上':'🚶 あるいて 2ふん'}, icon:'🗼', name:'さくら{湯|ゆ}', kind:'せんとう',
    open:[H(15), H(24)], rest:{dow:[1]}, restText:'げつようび',
    feat:['silk','yaku','sauna'], price:SEN.tokyo, baby:true,
    say:'スカイツリーの すぐ そば！ シルクの おふろも あるよ。',
    parent:'墨田区／シルク風呂・日替わり薬湯', q:'さくら湯 押上 銭湯' },
  { id:'daikokuyu-oshiage', at:{'押上':'🚶 あるいて 6ぷん'}, icon:'🌙', name:'{押上温泉|おしあげおんせん} {大黒湯|だいこくゆ}', kind:'せんとう',
    open:[H(15), H(34)], rest:{dow:[2]}, restText:'かようび',
    feat:['onsen','roten','tanso','yaku'], price:SEN.tokyo, baby:true,
    say:'おおきな そとの おふろの おんせん。つぎの ひの あさまで やってるよ。',
    parent:'墨田区／天然温泉・露天風呂・炭酸泉／翌朝10時まで営業', q:'押上温泉 大黒湯' }
];

const FEATURES = {
  roten: '🌳 そとの おふろ', onsen: '♨️ おんせん', sauna: '🔥 サウナ', denki: '⚡ でんきぶろ',
  ne: '🛌 ねころぶ おふろ', utase: '🚿 うたせゆ', awa: '🫧 あわぶろ', kuro: '⚫ くろい おゆ',
  kazoku: '👨‍👩‍👧 かぞくぶろ', car: '🚗 ちゅうしゃじょう', tile: '🖼️ タイルの え', many: '🎉 おふろ いっぱい',
  tanso: '🫧 しゅわしゅわ おふろ', nikai: '🏢 2かいだて', maki: '🪵 まきで わかす', penki: '🗻 ふじさんの え',
  bandai: '🧑‍🦳 ばんだい', yaku: '🌿 くすりの おふろ', asa: '🌅 あさから', retro: '📻 レトロ',
  silk: '🥛 シルクぶろ', niwa: '🎏 こいの いけ', rest: '🛋️ やすむ へや', ashiyu: '🦶 あしゆ',
  hinoki: '🌲 ひのきの おふろ', koi: '🐟 こいの すいそう',
  maru: '⭕ まあるい おふろ', uchu: '🚀 うちゅうの え'
};
