'use strict';

/*
 * 都道府県の もんだい データ
 *
 * もとデータは 同じリポジトリの ../nippon-sugoroku/data-prefs.js。
 * ルビ記法(漢字{よみ})を はずして、そのまま 出題に つかえる かたちに した。
 *
 *   name / kana         … 県の なまえ と よみ
 *   capital / capitalKana … 県庁所在地
 *   region              … どの 地方か(REGION_NAMES を みる)
 *   adj                 … となりの 県の id
 *   q / a / c           … その県の 名物クイズ(a が 3たく、c が せいかいの ばんごう)
 */

const REGION_NAMES = {
  hokkaido: { name: '北海道', kana: 'ほっかいどう', color: '#3f8fc0' },
  tohoku: { name: '東北', kana: 'とうほく', color: '#3f9e86' },
  kanto: { name: '関東', kana: 'かんとう', color: '#e0803c' },
  chubu: { name: '中部', kana: 'ちゅうぶ', color: '#6f9440' },
  kinki: { name: '近畿', kana: 'きんき', color: '#c25f83' },
  chugoku: { name: '中国', kana: 'ちゅうごく', color: '#7a6bbe' },
  shikoku: { name: '四国', kana: 'しこく', color: '#cf9a33' },
  kyushu: { name: '九州', kana: 'きゅうしゅう', color: '#d1584f' },
};

const PREFS_Q = [
  { id: 'hokkaido', name: '北海道', kana: 'ほっかいどう', capital: '札幌市', capitalKana: 'さっぽろし',
    region: 'hokkaido', adj: ['aomori'],
    q: '北海道で たくさん とれる 野菜は？', a: ['じゃがいも', 'さとうきび', 'みかん'], c: 0 },
  { id: 'aomori', name: '青森県', kana: 'あおもり', capital: '青森市', capitalKana: 'あおもりし',
    region: 'tohoku', adj: ['hokkaido', 'iwate', 'akita'],
    q: '青森県の 収穫量が 日本一の 果物は？', a: ['りんご', 'バナナ', 'ぶどう'], c: 0 },
  { id: 'iwate', name: '岩手県', kana: 'いわて', capital: '盛岡市', capitalKana: 'もりおかし',
    region: 'tohoku', adj: ['aomori', 'akita', 'miyagi'],
    q: '岩手県の 小さな お椀で 次々 食べる 麺は？', a: ['わんこそば', 'ラーメン', 'うどん'], c: 0 },
  { id: 'miyagi', name: '宮城県', kana: 'みやぎ', capital: '仙台市', capitalKana: 'せんだいし',
    region: 'tohoku', adj: ['iwate', 'akita', 'yamagata', 'fukushima'],
    q: '宮城県の 小さな 島が たくさん ある 景色は？', a: ['松島', '淡路島', '佐渡島'], c: 0 },
  { id: 'akita', name: '秋田県', kana: 'あきた', capital: '秋田市', capitalKana: 'あきたし',
    region: 'tohoku', adj: ['aomori', 'iwate', 'miyagi', 'yamagata'],
    q: '秋田県の 鬼の ような 姿の 神さまは？', a: ['なまはげ', '天狗', 'かっぱ'], c: 0 },
  { id: 'yamagata', name: '山形県', kana: 'やまがた', capital: '山形市', capitalKana: 'やまがたし',
    region: 'tohoku', adj: ['akita', 'miyagi', 'fukushima', 'niigata'],
    q: '山形県の 収穫量が 日本一の 果物は？', a: ['さくらんぼ', 'いちご', 'もも'], c: 0 },
  { id: 'fukushima', name: '福島県', kana: 'ふくしま', capital: '福島市', capitalKana: 'ふくしまし',
    region: 'tohoku', adj: ['miyagi', 'yamagata', 'niigata', 'gunma', 'tochigi', 'ibaraki'],
    q: '福島県の 首を 振る 赤い 牛の 玩具は？', a: ['赤べこ', 'こけし', 'だるま'], c: 0 },
  { id: 'ibaraki', name: '茨城県', kana: 'いばらき', capital: '水戸市', capitalKana: 'みとし',
    region: 'kanto', adj: ['fukushima', 'tochigi', 'saitama', 'chiba'],
    q: '茨城県の 水戸で 有名な ねばねばの 食べ物は？', a: ['納豆', '豆腐', 'こんにゃく'], c: 0 },
  { id: 'tochigi', name: '栃木県', kana: 'とちぎ', capital: '宇都宮市', capitalKana: 'うつのみやし',
    region: 'kanto', adj: ['fukushima', 'ibaraki', 'gunma', 'saitama'],
    q: '栃木県の 日光に いる 有名な 三びきの 動物は？', a: ['猿', '猫', '犬'], c: 0 },
  { id: 'gunma', name: '群馬県', kana: 'ぐんま', capital: '前橋市', capitalKana: 'まえばしし',
    region: 'kanto', adj: ['fukushima', 'tochigi', 'saitama', 'nagano', 'niigata'],
    q: '群馬県の 有名な 温泉は？', a: ['草津温泉', '道後温泉', '別府温泉'], c: 0 },
  { id: 'saitama', name: '埼玉県', kana: 'さいたま', capital: 'さいたま市', capitalKana: 'さいたまし',
    region: 'kanto', adj: ['gunma', 'tochigi', 'ibaraki', 'chiba', 'tokyo', 'yamanashi', 'nagano'],
    q: '埼玉県の「小江戸」と 呼ばれる 町は？', a: ['川越', '鎌倉', '倉敷'], c: 0 },
  { id: 'chiba', name: '千葉県', kana: 'ちば', capital: '千葉市', capitalKana: 'ちばし',
    region: 'kanto', adj: ['ibaraki', 'saitama', 'tokyo'],
    q: '千葉県の 収穫量が 日本一の 豆は？', a: ['落花生', 'あずき', '枝豆'], c: 0 },
  { id: 'tokyo', name: '東京都', kana: 'とうきょう', capital: '東京', capitalKana: 'とうきょう',
    region: 'kanto', adj: ['saitama', 'chiba', 'kanagawa', 'yamanashi'],
    q: '東京スカイツリーの 高さは？', a: ['634メートル', '333メートル', '100メートル'], c: 0 },
  { id: 'kanagawa', name: '神奈川県', kana: 'かながわ', capital: '横浜市', capitalKana: 'よこはまし',
    region: 'kanto', adj: ['tokyo', 'yamanashi', 'shizuoka'],
    q: '神奈川県の 鎌倉に ある 大きな 像は？', a: ['大仏', '大塔', '大船'], c: 0 },
  { id: 'niigata', name: '新潟県', kana: 'にいがた', capital: '新潟市', capitalKana: 'にいがたし',
    region: 'chubu', adj: ['yamagata', 'fukushima', 'gunma', 'nagano', 'toyama'],
    q: '新潟県の 収穫量が 日本一の 作物は？', a: ['お米', '麦', '芋'], c: 0 },
  { id: 'toyama', name: '富山県', kana: 'とやま', capital: '富山市', capitalKana: 'とやまし',
    region: 'chubu', adj: ['niigata', 'nagano', 'gifu', 'ishikawa'],
    q: '富山県の 立山に 春でも 残る 高い 壁は？', a: ['雪の 壁', '岩の 壁', '木の 壁'], c: 0 },
  { id: 'ishikawa', name: '石川県', kana: 'いしかわ', capital: '金沢市', capitalKana: 'かなざわし',
    region: 'chubu', adj: ['toyama', 'gifu', 'fukui'],
    q: '石川県の 金沢で 有名な ぴかぴかの ものは？', a: ['金箔', '銀貨', '銅線'], c: 0 },
  { id: 'fukui', name: '福井県', kana: 'ふくい', capital: '福井市', capitalKana: 'ふくいし',
    region: 'chubu', adj: ['ishikawa', 'gifu', 'shiga', 'kyoto'],
    q: '福井県で たくさん 見つかる 昔の 生き物の 化石は？', a: ['恐竜', 'マンモス', 'サメ'], c: 0 },
  { id: 'yamanashi', name: '山梨県', kana: 'やまなし', capital: '甲府市', capitalKana: 'こうふし',
    region: 'chubu', adj: ['saitama', 'tokyo', 'kanagawa', 'shizuoka', 'nagano'],
    q: '山梨県の 収穫量が 日本一の 果物は？', a: ['ぶどう', 'りんご', 'みかん'], c: 0 },
  { id: 'nagano', name: '長野県', kana: 'ながの', capital: '長野市', capitalKana: 'ながのし',
    region: 'chubu', adj: ['niigata', 'gunma', 'saitama', 'yamanashi', 'shizuoka', 'aichi', 'gifu', 'toyama'],
    q: '高い 山が 多い 長野県の 呼び名は？', a: ['日本の屋根', '日本の庭', '日本の海'], c: 0 },
  { id: 'gifu', name: '岐阜県', kana: 'ぎふ', capital: '岐阜市', capitalKana: 'ぎふし',
    region: 'chubu', adj: ['toyama', 'ishikawa', 'fukui', 'nagano', 'aichi', 'mie', 'shiga'],
    q: '岐阜県の 白川郷の 屋根の 形の 名前は？', a: ['合掌造り', '寝殿造り', '校倉造り'], c: 0 },
  { id: 'shizuoka', name: '静岡県', kana: 'しずおか', capital: '静岡市', capitalKana: 'しずおかし',
    region: 'chubu', adj: ['kanagawa', 'yamanashi', 'nagano', 'aichi'],
    q: '日本で 一番 高い 山は？', a: ['富士山', '高尾山', '阿蘇山'], c: 0 },
  { id: 'aichi', name: '愛知県', kana: 'あいち', capital: '名古屋市', capitalKana: 'なごやし',
    region: 'chubu', adj: ['shizuoka', 'nagano', 'gifu', 'mie'],
    q: '名古屋城の 屋根に のっている 金色の ものは？', a: ['しゃちほこ', '鳥', '竜'], c: 0 },
  { id: 'mie', name: '三重県', kana: 'みえ', capital: '津市', capitalKana: 'つし',
    region: 'kinki', adj: ['aichi', 'gifu', 'shiga', 'kyoto', 'nara', 'wakayama'],
    q: '三重県の 海に 潜って 貝を とる 人を 何と 呼ぶ？', a: ['海女', '船長', '灯台守'], c: 0 },
  { id: 'shiga', name: '滋賀県', kana: 'しが', capital: '大津市', capitalKana: 'おおつし',
    region: 'kinki', adj: ['fukui', 'gifu', 'mie', 'kyoto'],
    q: '日本で 一番 大きな 湖は？', a: ['琵琶湖', '霞ヶ浦', '十和田湖'], c: 0 },
  { id: 'kyoto', name: '京都府', kana: 'きょうと', capital: '京都市', capitalKana: 'きょうとし',
    region: 'kinki', adj: ['fukui', 'shiga', 'mie', 'nara', 'osaka', 'hyogo'],
    q: '京都の 金色に 輝く お寺は？', a: ['金閣寺', '東大寺', '善光寺'], c: 0 },
  { id: 'osaka', name: '大阪府', kana: 'おおさか', capital: '大阪市', capitalKana: 'おおさかし',
    region: 'kinki', adj: ['kyoto', 'nara', 'wakayama', 'hyogo'],
    q: '大阪で 生まれた たこの 入った 丸い 食べ物は？', a: ['たこ焼き', 'たい焼き', 'おはぎ'], c: 0 },
  { id: 'hyogo', name: '兵庫県', kana: 'ひょうご', capital: '神戸市', capitalKana: 'こうべし',
    region: 'kinki', adj: ['kyoto', 'osaka', 'tottori', 'okayama', 'tokushima'],
    q: '兵庫県の 白い お城の 名前は？', a: ['姫路城', '熊本城', '松本城'], c: 0 },
  { id: 'nara', name: '奈良県', kana: 'なら', capital: '奈良市', capitalKana: 'ならし',
    region: 'kinki', adj: ['kyoto', 'mie', 'osaka', 'wakayama'],
    q: '奈良公園に たくさん いる 動物は？', a: ['鹿', '猿', 'うさぎ'], c: 0 },
  { id: 'wakayama', name: '和歌山県', kana: 'わかやま', capital: '和歌山市', capitalKana: 'わかやまし',
    region: 'kinki', adj: ['mie', 'nara', 'osaka', 'tokushima'],
    q: '和歌山県の 収穫量が 日本一の 果物は？', a: ['みかん', 'なし', 'かき'], c: 0 },
  { id: 'tottori', name: '鳥取県', kana: 'とっとり', capital: '鳥取市', capitalKana: 'とっとりし',
    region: 'chugoku', adj: ['hyogo', 'okayama', 'hiroshima', 'shimane'],
    q: '鳥取県に ある 砂の 大きな 丘は？', a: ['砂丘', '火山', '鍾乳洞'], c: 0 },
  { id: 'shimane', name: '島根県', kana: 'しまね', capital: '松江市', capitalKana: 'まつえし',
    region: 'chugoku', adj: ['tottori', 'hiroshima', 'yamaguchi'],
    q: '島根県の 神さまが 集まると いわれる 神社は？', a: ['出雲大社', '伊勢神宮', '明治神宮'], c: 0 },
  { id: 'okayama', name: '岡山県', kana: 'おかやま', capital: '岡山市', capitalKana: 'おかやまし',
    region: 'chugoku', adj: ['hyogo', 'tottori', 'hiroshima', 'kagawa'],
    q: '岡山県に 伝わる 昔話の 主人公は？', a: ['桃太郎', '浦島太郎', '金太郎'], c: 0 },
  { id: 'hiroshima', name: '広島県', kana: 'ひろしま', capital: '広島市', capitalKana: 'ひろしまし',
    region: 'chugoku', adj: ['okayama', 'tottori', 'shimane', 'yamaguchi', 'ehime'],
    q: '広島県の 宮島で 海に 立っている 赤い ものは？', a: ['鳥居', '灯台', '柱'], c: 0 },
  { id: 'yamaguchi', name: '山口県', kana: 'やまぐち', capital: '山口市', capitalKana: 'やまぐちし',
    region: 'chugoku', adj: ['shimane', 'hiroshima', 'fukuoka'],
    q: '山口県の 下関で 有名な 魚は？', a: ['ふぐ', 'さんま', 'さけ'], c: 0 },
  { id: 'tokushima', name: '徳島県', kana: 'とくしま', capital: '徳島市', capitalKana: 'とくしまし',
    region: 'shikoku', adj: ['kagawa', 'ehime', 'kochi', 'hyogo', 'wakayama'],
    q: '徳島県の 夏の 有名な 踊りは？', a: ['阿波おどり', 'よさこい', 'エイサー'], c: 0 },
  { id: 'kagawa', name: '香川県', kana: 'かがわ', capital: '高松市', capitalKana: 'たかまつし',
    region: 'shikoku', adj: ['tokushima', 'ehime', 'okayama'],
    q: '日本で 一番 面積が 小さい 県は？', a: ['香川県', '大阪府', '東京都'], c: 0 },
  { id: 'ehime', name: '愛媛県', kana: 'えひめ', capital: '松山市', capitalKana: 'まつやまし',
    region: 'shikoku', adj: ['kagawa', 'tokushima', 'kochi', 'hiroshima'],
    q: '愛媛県の とても 古い 有名な 温泉は？', a: ['道後温泉', '草津温泉', '有馬温泉'], c: 0 },
  { id: 'kochi', name: '高知県', kana: 'こうち', capital: '高知市', capitalKana: 'こうちし',
    region: 'shikoku', adj: ['tokushima', 'ehime'],
    q: '高知県の 有名な 魚料理は？', a: ['かつおの たたき', 'さばの みそ煮', 'いわしの 干物'], c: 0 },
  { id: 'fukuoka', name: '福岡県', kana: 'ふくおか', capital: '福岡市', capitalKana: 'ふくおかし',
    region: 'kyushu', adj: ['yamaguchi', 'saga', 'oita', 'kumamoto'],
    q: '福岡県の 夜の 道に 出る 小さな お店を 何と 呼ぶ？', a: ['屋台', '小屋', '車'], c: 0 },
  { id: 'saga', name: '佐賀県', kana: 'さが', capital: '佐賀市', capitalKana: 'さがし',
    region: 'kyushu', adj: ['fukuoka', 'nagasaki'],
    q: '佐賀県の 有名な 焼き物は？', a: ['有田焼', '信楽焼', '備前焼'], c: 0 },
  { id: 'nagasaki', name: '長崎県', kana: 'ながさき', capital: '長崎市', capitalKana: 'ながさきし',
    region: 'kyushu', adj: ['saga', 'kumamoto'],
    q: '長崎県に 昔 あった 外国と 貿易を した 島は？', a: ['出島', '淡路島', '佐渡島'], c: 0 },
  { id: 'kumamoto', name: '熊本県', kana: 'くまもと', capital: '熊本市', capitalKana: 'くまもとし',
    region: 'kyushu', adj: ['fukuoka', 'oita', 'miyazaki', 'kagoshima', 'nagasaki'],
    q: '熊本県に ある 大きな 火山は？', a: ['阿蘇山', '富士山', '浅間山'], c: 0 },
  { id: 'oita', name: '大分県', kana: 'おおいた', capital: '大分市', capitalKana: 'おおいたし',
    region: 'kyushu', adj: ['fukuoka', 'kumamoto', 'miyazaki'],
    q: '大分県が 日本一なのは 何？', a: ['温泉の 湧き出る 量', '雪の 量', '砂丘の 広さ'], c: 0 },
  { id: 'miyazaki', name: '宮崎県', kana: 'みやざき', capital: '宮崎市', capitalKana: 'みやざきし',
    region: 'kyushu', adj: ['oita', 'kumamoto', 'kagoshima'],
    q: '宮崎県の 甘い 南の 果物は？', a: ['マンゴー', 'りんご', 'さくらんぼ'], c: 0 },
  { id: 'kagoshima', name: '鹿児島県', kana: 'かごしま', capital: '鹿児島市', capitalKana: 'かごしまし',
    region: 'kyushu', adj: ['kumamoto', 'miyazaki', 'okinawa'],
    q: '鹿児島県の 今も 煙を 上げる 火山は？', a: ['桜島', '阿蘇山', '雲仙岳'], c: 0 },
  { id: 'okinawa', name: '沖縄県', kana: 'おきなわ', capital: '那覇市', capitalKana: 'なはし',
    region: 'kyushu', adj: ['kagoshima'],
    q: '沖縄県の 太鼓を たたく 有名な 踊りは？', a: ['エイサー', '阿波おどり', '盆おどり'], c: 0 },
];

const PREF_BY_ID = {};
PREFS_Q.forEach((p) => { PREF_BY_ID[p.id] = p; });
