/* にっぽん一周すごろく - ひみつのカード 100まい
 * pref: そのカードが みつかる とどうふけん
 * cat : しゅるい（CARD_CATS の キー）
 * rare: 1=ふつう 2=めずらしい 3=でんせつ（でんせつは もくてきち とうちゃくで もらえる）
 */
const CARD_CATS = {
  food:   { label:'たべもの', emoji:'🍙', color:'#e0785a' },
  place:  { label:'めいしょ', emoji:'🏯', color:'#6d8fd0' },
  nature: { label:'しぜん',   emoji:'🌸', color:'#5aa87a' },
  fest:   { label:'おまつり', emoji:'🎊', color:'#d4713f' },
  craft:  { label:'こうげい', emoji:'🎨', color:'#b07cc6' },
  ride:   { label:'のりもの', emoji:'🚄', color:'#4aa3c7' },
  animal: { label:'いきもの', emoji:'🐾', color:'#c99a3f' },
};

const CARDS = [
  { id:1,  pref:'hokkaido', cat:'food',   rare:1, name:'かいせんどん',           text:'とれたての かにや いくらが どーんと のった どんぶり。' },
  { id:2,  pref:'hokkaido', cat:'fest',   rare:2, name:'ゆきまつりの ゆきぞう',  text:'さっぽろの おおどおりに ならぶ、ビルほど おおきな ゆきの ぞう。' },
  { id:3,  pref:'aomori',   cat:'food',   rare:1, name:'あおもりの りんご',      text:'しゅうかくりょう にほんいち。あきに まっかに みのるよ。' },
  { id:4,  pref:'aomori',   cat:'fest',   rare:1, name:'ねぶた',                 text:'ひかる おおきな にんぎょうの やまが よるの まちを ねりあるく。' },
  { id:5,  pref:'iwate',    cat:'food',   rare:1, name:'わんこそば',             text:'ちいさな おわんに つぎつぎ そばが。100ぱい たべる ひとも いるよ。' },
  { id:6,  pref:'iwate',    cat:'place',  rare:2, name:'こんじきどう',           text:'ちゅうそんじの きんいろに かがやく おどう。900ねん まえの たてもの。' },
  { id:7,  pref:'miyagi',   cat:'food',   rare:1, name:'ぎゅうたん',             text:'せんだいで うまれた こうばしい やきにく。' },
  { id:8,  pref:'miyagi',   cat:'nature', rare:1, name:'まつしま',               text:'260いじょうの ちいさな しまが うみに うかぶ にほんさんけい。' },
  { id:9,  pref:'akita',    cat:'fest',   rare:2, name:'なまはげ',               text:'おおみそかに「わるいこは いねがー」と いえを たずねる かみさま。' },
  { id:10, pref:'akita',    cat:'food',   rare:1, name:'きりたんぽ',             text:'ごはんを ぼうに まいて やき、なべに いれて たべるよ。' },
  { id:11, pref:'yamagata', cat:'food',   rare:1, name:'さくらんぼ',             text:'つやつや あかい みが ふたつ ならんで つくよ。' },
  { id:12, pref:'yamagata', cat:'place',  rare:1, name:'ぎんざんおんせん',       text:'かわぞいに きの りょかんが ならび、よるは ガスとうが ともる。' },
  { id:13, pref:'fukushima',cat:'craft',  rare:1, name:'あかべこ',               text:'くびを ゆらゆら ふる あかい うしの きょうどがんぐ。' },
  { id:14, pref:'fukushima',cat:'place',  rare:1, name:'つるがじょう',           text:'あいづわかまつの しろ。あかい かわらの やねが めじるし。' },
  { id:15, pref:'ibaraki',  cat:'food',   rare:1, name:'なっとう',               text:'だいずを はっこうさせた ねばねばの たべもの。' },
  { id:16, pref:'ibaraki',  cat:'nature', rare:1, name:'かいらくえんの うめ',    text:'3000ぼんの うめが はるに いっせいに さくよ。' },
  { id:17, pref:'tochigi',  cat:'place',  rare:2, name:'にっこうとうしょうぐう', text:'「みざる・きかざる・いわざる」の さんざるが ほられた やしろ。' },
  { id:18, pref:'tochigi',  cat:'food',   rare:1, name:'とちおとめ',             text:'とちぎけんで うまれた あまい いちご。' },
  { id:19, pref:'gunma',    cat:'place',  rare:1, name:'くさつおんせん',         text:'あつい おゆを おおきな いたで まぜて さます「ゆもみ」が めいぶつ。' },
  { id:20, pref:'gunma',    cat:'craft',  rare:1, name:'たかさきだるま',         text:'ねがいごとを して かたほうの めを かきいれる あかい だるま。' },
  { id:21, pref:'saitama',  cat:'place',  rare:1, name:'ときのかね',             text:'かわごえの まちに 400ねん まえから ときを つげる かねつき どう。' },
  { id:22, pref:'saitama',  cat:'food',   rare:1, name:'そうかせんべい',         text:'おこめを のばして やいた かたい しょうゆあじの せんべい。' },
  { id:23, pref:'chiba',    cat:'food',   rare:1, name:'らっかせい',             text:'つちの なかで みが そだつ まめ。しゅうかく にほんいち。' },
  { id:24, pref:'chiba',    cat:'ride',   rare:1, name:'なりたの ひこうき',      text:'せかいじゅうへ とびたつ おおきな ジェットき。' },
  { id:25, pref:'tokyo',    cat:'place',  rare:2, name:'とうきょうスカイツリー', text:'たかさ 634メートル。にほんで いちばん たかい とう。' },
  { id:26, pref:'tokyo',    cat:'food',   rare:1, name:'もんじゃやき',           text:'てっぱんの うえで とろとろに やいて、へらで すくって たべる。' },
  { id:27, pref:'kanagawa', cat:'place',  rare:1, name:'かまくらの だいぶつ',    text:'そとの そらの したに すわる たかさ やく 13メートルの ほとけさま。' },
  { id:28, pref:'kanagawa', cat:'food',   rare:1, name:'よこはまの しゅうまい',  text:'ちゅうかがいで うまれた ひとくちサイズの てんしん。' },
  { id:29, pref:'niigata',  cat:'food',   rare:1, name:'こしひかり',             text:'つやつや あまい にほんいちの ブランドまい。' },
  { id:30, pref:'niigata',  cat:'animal', rare:2, name:'さどの トキ',            text:'うすい ももいろの はねを もつ とり。さどがしまで まもられているよ。' },
  { id:31, pref:'toyama',   cat:'food',   rare:1, name:'ますのすし',             text:'ささの はで つつんだ まるい おすし。' },
  { id:32, pref:'toyama',   cat:'nature', rare:2, name:'ゆきのおおたに',         text:'たてやまの みちの りょうがわに たつ 10メートルの ゆきの かべ。' },
  { id:33, pref:'ishikawa', cat:'place',  rare:1, name:'けんろくえん',           text:'にほんさんめいえんの ひとつ。ふゆの ゆきづりが うつくしい。' },
  { id:34, pref:'ishikawa', cat:'craft',  rare:2, name:'きんぱく',               text:'かみより うすく のばした きん。かなざわで ほとんどが つくられる。' },
  { id:35, pref:'fukui',    cat:'nature', rare:2, name:'きょうりゅうの かせき',  text:'ふくいで みつかった きょうりゅうには「フクイラプトル」も いるよ。' },
  { id:36, pref:'fukui',    cat:'food',   rare:1, name:'えちぜんがに',           text:'ふゆの にほんかいで とれる おおきな ずわいがに。' },
  { id:37, pref:'yamanashi',cat:'food',   rare:1, name:'こうしゅうぶどう',       text:'にほんで むかしから そだてられてきた ぶどう。' },
  { id:38, pref:'yamanashi',cat:'nature', rare:1, name:'ふじごこ',               text:'ふじさんの きたがわに ならぶ 5つの みずうみ。' },
  { id:39, pref:'nagano',   cat:'food',   rare:1, name:'しんしゅうそば',         text:'すずしい たかちで そだった そばこで うつ めん。' },
  { id:40, pref:'nagano',   cat:'animal', rare:2, name:'おんせんザル',           text:'ゆきの なか おんせんに つかる にほんザル。せかいで ここだけ。' },
  { id:41, pref:'gifu',     cat:'place',  rare:2, name:'しらかわごうの がっしょうづくり', text:'てを あわせた かたちの やねの いえ。せかいいさん。' },
  { id:42, pref:'gifu',     cat:'fest',   rare:1, name:'ながらがわの うかい',    text:'ウという とりを つかって あゆを とる 1300ねんの ぎょほう。' },
  { id:43, pref:'shizuoka', cat:'nature', rare:1, name:'ちゃばたけ',             text:'まるい かたちの ちゃのきが やまの しゃめんに ならぶ。' },
  { id:44, pref:'shizuoka', cat:'food',   rare:1, name:'はままつの うなぎ',      text:'はまなこの ちかくで そだった うなぎの かばやき。' },
  { id:45, pref:'aichi',    cat:'place',  rare:1, name:'きんの しゃちほこ',      text:'なごやじょうの やねに のる きんいろの さかなの かざり。' },
  { id:46, pref:'aichi',    cat:'food',   rare:1, name:'てばさき',               text:'あまからい たれと こしょうが きいた とりの てば。' },
  { id:47, pref:'mie',      cat:'craft',  rare:2, name:'しんじゅ',               text:'あこやがいの なかで そだつ しろく ひかる たま。' },
  { id:48, pref:'mie',      cat:'place',  rare:1, name:'いせじんぐう',           text:'20ねんごとに おやしろを たてなおす「しきねんせんぐう」が つづく。' },
  { id:49, pref:'shiga',    cat:'nature', rare:1, name:'びわこ',                 text:'にほんいち おおきな みずうみ。しがけんの 6ぶんの 1を しめる。' },
  { id:50, pref:'shiga',    cat:'craft',  rare:1, name:'しがらきの たぬき',      text:'おみせの まえに たつ、かさを かぶった やきものの たぬき。' },
  { id:51, pref:'kyoto',    cat:'place',  rare:2, name:'きんかくじ',             text:'きんぱくで つつまれた 3かいだての おどう。' },
  { id:52, pref:'kyoto',    cat:'food',   rare:1, name:'うじまっちゃ',           text:'こなに した みどりの おちゃ。おかしにも つかわれるよ。' },
  { id:53, pref:'osaka',    cat:'food',   rare:1, name:'たこやき',               text:'まるい てっぱんで やく、たこの はいった たべあるきの めいぶつ。' },
  { id:54, pref:'osaka',    cat:'place',  rare:1, name:'おおさかじょう',         text:'とよとみひでよしが たてた しろ。みどりの やねが めじるし。' },
  { id:55, pref:'hyogo',    cat:'place',  rare:2, name:'ひめじじょう',           text:'しろい かべから「しらさぎじょう」と よばれる せかいいさん。' },
  { id:56, pref:'hyogo',    cat:'food',   rare:2, name:'こうべビーフ',           text:'ひょうごけんで そだった くろげわぎゅうの とくべつな にく。' },
  { id:57, pref:'nara',     cat:'place',  rare:2, name:'とうだいじの だいぶつ',  text:'たかさ やく 15メートル。1300ねん まえに つくられた。' },
  { id:58, pref:'nara',     cat:'animal', rare:1, name:'ならの しか',            text:'ならこうえんに 1000とう いじょう。おじぎを する しかも いるよ。' },
  { id:59, pref:'wakayama', cat:'food',   rare:1, name:'ありだみかん',           text:'しゅうかく にほんいち。あまくて じょうぶな かわ。' },
  { id:60, pref:'wakayama', cat:'nature', rare:2, name:'くまのこどう',           text:'やまの なかを とおる まいりみち。せかいいさんの みち。' },
  { id:61, pref:'tottori',  cat:'nature', rare:2, name:'とっとりさきゅう',       text:'ながさ 16キロも つづく すなの おか。かぜが もようを つくる。' },
  { id:62, pref:'tottori',  cat:'food',   rare:1, name:'にじゅっせいきなし',     text:'きみどりいろで しゃりしゃりした なし。' },
  { id:63, pref:'shimane',  cat:'place',  rare:2, name:'いずもたいしゃ',         text:'10がつに にほんじゅうの かみさまが あつまると いわれる やしろ。' },
  { id:64, pref:'shimane',  cat:'food',   rare:1, name:'しんじこの しじみ',      text:'こい だしが でる ちいさな くろい かい。' },
  { id:65, pref:'okayama',  cat:'food',   rare:1, name:'きびだんご',             text:'ももたろうが おともに わたした まるい おだんご。' },
  { id:66, pref:'okayama',  cat:'place',  rare:1, name:'くらしきの しろかべ',    text:'かわぞいに しろい かべの くらが ならぶ ふるい まちなみ。' },
  { id:67, pref:'hiroshima',cat:'place',  rare:2, name:'みやじまの おおとりい',  text:'しおが みちると うみに うかんで みえる あかい とりい。' },
  { id:68, pref:'hiroshima',cat:'food',   rare:1, name:'ひろしまおこのみやき',   text:'そばを はさんで かさねて やく おこのみやき。' },
  { id:69, pref:'yamaguchi',cat:'nature', rare:1, name:'あきよしだい',           text:'しろい いわが てんてんと ならぶ くさはら。ちかには おおきな どうくつ。' },
  { id:70, pref:'yamaguchi',cat:'food',   rare:2, name:'しものせきの ふぐ',      text:'ふゆの めいぶつ。うすく きって おさらに はなの ように ならべる。' },
  { id:71, pref:'tokushima',cat:'fest',   rare:2, name:'あわおどり',             text:'400ねん つづく なつの おどり。まちじゅうが れんに なって おどる。' },
  { id:72, pref:'tokushima',cat:'nature', rare:1, name:'なるとの うずしお',      text:'かいきょうの しおの ながれが つくる おおきな うず。' },
  { id:73, pref:'kagawa',   cat:'food',   rare:1, name:'さぬきうどん',           text:'こしが つよい ふとい めん。けんない に 500けん いじょうの おみせ。' },
  { id:74, pref:'kagawa',   cat:'place',  rare:1, name:'こんぴらさん',           text:'785だんの ながい いしだんを のぼった さきに ある おみや。' },
  { id:75, pref:'ehime',    cat:'place',  rare:2, name:'どうごおんせん',         text:'にほんで いちばん ふるいと いわれる おんせんの ひとつ。' },
  { id:76, pref:'ehime',    cat:'food',   rare:1, name:'いよかん',               text:'かおりが よくて じょうが やわらかい かんきつ。' },
  { id:77, pref:'kochi',    cat:'food',   rare:1, name:'かつおの たたき',        text:'わらの ほのおで さっと やいて、しおや ゆずで たべる。' },
  { id:78, pref:'kochi',    cat:'nature', rare:2, name:'しまんとがわ',           text:'「さいごの せいりゅう」と よばれる すきとおった かわ。' },
  { id:79, pref:'fukuoka',  cat:'place',  rare:1, name:'はかたの やたい',        text:'よるに でる ちいさな おみせ。ラーメンや おでんが たべられる。' },
  { id:80, pref:'fukuoka',  cat:'food',   rare:1, name:'めんたいこ',             text:'すけとうだらの たまごを ぴりからに つけこんだ たべもの。' },
  { id:81, pref:'saga',     cat:'craft',  rare:2, name:'ありたやき',             text:'しろい はだに あおや あかの もようを えがいた やきもの。' },
  { id:82, pref:'saga',     cat:'ride',   rare:1, name:'ききゅう',               text:'あきに さがの そらを いろとりどりの ききゅうが うめつくす。' },
  { id:83, pref:'nagasaki', cat:'place',  rare:2, name:'でじま',                 text:'えどじだいに がいこくと ぼうえきを した おうぎがたの しま。' },
  { id:84, pref:'nagasaki', cat:'food',   rare:1, name:'カステラ',               text:'なんばんぼうえきで つたわった ふんわり あまい やきがし。' },
  { id:85, pref:'kumamoto', cat:'nature', rare:2, name:'あそさん',               text:'せかいでも おおきな カルデラを もつ かざん。' },
  { id:86, pref:'kumamoto', cat:'place',  rare:1, name:'くまもとじょう',         text:'そりかえった いしがきが「むしゃがえし」と よばれる しろ。' },
  { id:87, pref:'oita',     cat:'place',  rare:1, name:'べっぷの じごく',        text:'あおや あかの おゆが ぼこぼこ わきでる おんせんの めいしょ。' },
  { id:88, pref:'oita',     cat:'food',   rare:1, name:'とりてん',               text:'とりにくを てんぷらに した おおいたの ていばんりょうり。' },
  { id:89, pref:'miyazaki', cat:'food',   rare:1, name:'みやざきマンゴー',       text:'たいようを たっぷり あびた とろける あまさの くだもの。' },
  { id:90, pref:'miyazaki', cat:'nature', rare:2, name:'たかちほきょう',         text:'ようがんが けずられて できた ふかい たにと たき。' },
  { id:91, pref:'kagoshima',cat:'nature', rare:2, name:'さくらじま',             text:'いまも けむりを あげる かざん。まちに はいが ふることも。' },
  { id:92, pref:'kagoshima',cat:'food',   rare:1, name:'さつまあげ',             text:'さかなの すりみを あげた こうばしい たべもの。' },
  { id:93, pref:'okinawa',  cat:'place',  rare:2, name:'しゅりじょう',           text:'りゅうきゅうおうこくの あかい おしろ。' },
  { id:94, pref:'okinawa',  cat:'fest',   rare:2, name:'エイサー',               text:'おおきな たいこを たたきながら まちを ねりあるく おどり。' },

  /* ── でんせつカード：もくてきちに とうちゃくすると もらえる ── */
  { id:95,  pref:'shizuoka', cat:'nature', rare:3, name:'ふじさん',              text:'たかさ 3776メートル。にほんいちの やまで、せかいいさん。' },
  { id:96,  pref:'tokyo',    cat:'ride',   rare:3, name:'しんかんせん',          text:'1964ねんに はしりはじめた にほんの こうそくれっしゃ。' },
  { id:97,  pref:'kagawa',   cat:'ride',   rare:3, name:'せとおおはし',          text:'ほんしゅうと しこくを むすぶ ながさ 9.4キロの はし。' },
  { id:98,  pref:'aomori',   cat:'nature', rare:3, name:'しらかみさんちの ブナ',  text:'にんげんの てが ほとんど はいっていない ブナの もり。せかいいさん。' },
  { id:99,  pref:'kagoshima',cat:'nature', rare:3, name:'じょうもんすぎ',        text:'やくしまに たつ すいてい 2000ねん いじょうの すぎの たいぼく。' },
  { id:100, pref:'hokkaido', cat:'animal', rare:3, name:'タンチョウ',            text:'くしろしつげんに すむ しろと くろの おおきな つる。' },
];
